"""operations_control.onboarding.artefacts — approved answers -> Trakt configuration.

Generation is driven by the catalogue: each field declares the artefact and key
path it writes into (``writes_to``), and this module routes values accordingly.
Adding a field to the catalogue therefore reaches the generated configuration
without a change here.

Two properties matter and are tested:

* **Deterministic** — the same answers produce byte-identical documents. Nothing
  reads the clock, the filesystem or a random source during rendering.
* **Idempotent** — re-running an approved case writes the same thing again.
  Re-activation is a no-op, not a second set of records.

Generation never copies another client. A new client's documents are built from
its own answers; ``base_documents`` (a migration's legacy files) only preserve
blocks onboarding does not own.
"""

from __future__ import annotations

import copy
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import yaml

from apps.blob_trigger_app.source_registry import (
    STATUS_ACTIVE,
    STATUS_PENDING_REVIEW,
    SourceRecord,
    SourceRegistry,
)

from ..configuration.packages import ASSET_MODEL
from .case import OnboardingCase
from .catalogue import Catalogue, Field, catalogue
from .derivation import blob_prefix

ARTEFACT_CLIENT_CONFIG = "client_config"
ARTEFACT_ANNEX12_CONFIG = "annex12_config"
ARTEFACT_PORTFOLIO_REGISTRY = "portfolio_registry"
ARTEFACT_SOURCE_REGISTRY = "source_registry"
ARTEFACT_TENANCY = "tenancy"
ARTEFACT_ONBOARDING_RECORD = "onboarding_record"

ARTEFACT_LABELS = {
    ARTEFACT_CLIENT_CONFIG: "Client configuration",
    ARTEFACT_ANNEX12_CONFIG: "Investor report configuration",
    ARTEFACT_PORTFOLIO_REGISTRY: "Portfolio metadata",
    ARTEFACT_SOURCE_REGISTRY: "Source registrations",
    ARTEFACT_TENANCY: "Client index",
    ARTEFACT_ONBOARDING_RECORD: "Onboarding record",
}

GENERATED_BANNER = (
    "# GENERATED by the Trakt Operations Control Centre — Client Onboarding.\n"
    "# This file is a governed artefact. Change it through Client Onboarding,\n"
    "# not by hand: a hand edit is not versioned, not attributed and not\n"
    "# audited, and the next approved change will overwrite it.\n"
)


def client_config_rel(client_id: str) -> str:
    return f"config/client/config_client_{client_id}.yaml"


def annex12_config_rel(client_id: str) -> str:
    return f"config/client/config_client_{client_id}_annex12.yaml"


def portfolio_registry_rel(client_id: str) -> str:
    return f"config/client/portfolio_registry_{client_id}.yaml"


def tenancy_rel(client_id: str) -> str:
    return f"config/client/client_index_{client_id}.yaml"


@dataclass
class Artefact:
    kind: str
    rel: str
    label: str
    action: str                     # create | update | unchanged
    text: str = ""
    previous_text: str = ""
    records: List[Dict[str, Any]] = field(default_factory=list)
    summary: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #

def _deep_set(node: Dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    for part in parts[:-1]:
        nxt = node.get(part)
        if not isinstance(nxt, dict):
            nxt = {}
            node[part] = nxt
        node = nxt
    node[parts[-1]] = value


def _deep_get(node: Any, dotted: str) -> Any:
    for part in dotted.split("."):
        if not isinstance(node, dict):
            return None
        node = node.get(part)
    return node


def _dump(doc: Dict[str, Any]) -> str:
    return GENERATED_BANNER + yaml.safe_dump(doc, sort_keys=False,
                                             allow_unicode=True)


def _parse(text: Optional[str]) -> Dict[str, Any]:
    if not text:
        return {}
    try:
        return yaml.safe_load(text) or {}
    except yaml.YAMLError:
        return {}


def _present(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, bool):
        return True
    if isinstance(value, (list, tuple, dict)):
        return bool(value)
    return bool(str(value).strip())


def _coerce(f: Field, value: Any) -> Any:
    """Normalise a value the way its declared type requires."""
    if isinstance(value, bool):
        return value
    text = str(value).strip()
    if f.type in ("lei", "country", "currency") or \
            f.validation in ("lei", "country", "currency"):
        return text.upper()
    if f.type == "boolean":
        return str(value).strip().lower() in ("true", "yes", "y", "1")
    return text


def _action(previous: Optional[str], text: str) -> str:
    if previous is None:
        return "create"
    return "unchanged" if previous == text else "update"


# --------------------------------------------------------------------------- #
# Routing: catalogue writes_to -> document
# --------------------------------------------------------------------------- #

def _route(cat: Catalogue, case: OnboardingCase,
           kind: str) -> List[Tuple[Field, str, Any]]:
    """Every (field, dotted path, value) destined for one artefact kind."""
    out: List[Tuple[Field, str, Any]] = []
    prefix = f"{kind}:"
    for section in cat.sections:
        if section.repeatable:
            continue                     # handled per-record below
        if section.from_regime:
            held = case.answers.get(section.key) or {}
            for f in section.fields:
                if not str(f.writes_to).startswith(prefix):
                    continue
                if f.product and f.product not in case.products:
                    continue
                value = (held.get(f.product) or {}).get(f.key)
                if _present(value):
                    out.append((f, f.writes_to[len(prefix):], value))
            continue
        block = case.answers.get(section.key) or {}
        for f in section.fields:
            if not str(f.writes_to).startswith(prefix):
                continue
            value = block.get(f.key)
            if not _present(value) and f.default is not None:
                value = f.default
            if _present(value):
                out.append((f, f.writes_to[len(prefix):], value))
    return out


# --------------------------------------------------------------------------- #
# Client configuration
# --------------------------------------------------------------------------- #

def render_client_config(case: OnboardingCase, *,
                         cat: Optional[Catalogue] = None,
                         base: Optional[Dict[str, Any]] = None
                         ) -> Tuple[Dict[str, Any], List[str]]:
    """The master client configuration, in the shape every existing reader
    expects, built from this client's own answers."""
    cat = cat or catalogue()
    doc = copy.deepcopy(base) if base else {}
    notes: List[str] = []

    for f, dotted, value in _route(cat, case, ARTEFACT_CLIENT_CONFIG):
        _deep_set(doc, dotted, _coerce(f, value))

    client = case.answers.get("client") or {}
    if client.get("client_name"):
        notes.append(f"Client identity for {client['client_name']}.")

    # The legacy `portfolio:` block is single-valued and describes the client's
    # dominant book. Per-portfolio detail lives in the portfolio metadata; this
    # keeps every existing reader working.
    portfolios = case.items("portfolios")
    if portfolios:
        _deep_set(doc, "portfolio.asset_class",
                  str(portfolios[0].get("asset_class") or ""))
        notes.append("Portfolio jurisdiction and reporting currency.")

    # Regime capability, from the asset support model rather than a restatement.
    supported: List[str] = []
    for p in portfolios:
        for regime in (ASSET_MODEL.get(str(p.get("asset_class") or ""), {})
                       .get("supports_regimes") or []):
            if regime not in supported:
                supported.append(regime)
    products = case.products
    if "investor_reporting" in products:
        annex12 = ((cat.regime_products.get("investor_reporting") or {})
                   .get("regime_id") or "ESMA_Annex12")
        if annex12 not in supported:
            supported.append(annex12)
    if supported:
        doc["supported_regimes"] = supported
        chosen = ("ESMA_Annex2" if "esma_annex2" in products
                  and "ESMA_Annex2" in supported else supported[0])
        doc["default_regime"] = chosen
        doc["regime"] = chosen           # legacy compatibility key
        notes.append("Regime capability set: " + ", ".join(supported) + ".")

    pipeline = doc.get("pipeline")
    if not isinstance(pipeline, dict):
        pipeline = {}
    doc["pipeline"] = pipeline
    pipeline.setdefault("loan_engine_enabled", False)
    pipeline["mi_enabled"] = True
    pipeline["esma_enabled"] = "esma_annex2" in products
    notes.append("Reporting products: "
                 + (", ".join(sorted(products)) or "management information only")
                 + ".")

    # The UK geography override carries a governed shape, not just a flag.
    if _deep_get(doc, "regime_overrides.ESMA_Annex2.uk_geography.enabled"):
        _deep_set(doc, "regime_overrides.ESMA_Annex2.uk_geography.override_value",
                  "GBZZZ")
        _deep_set(doc, "regime_overrides.ESMA_Annex2.uk_geography.target_fields",
                  ["geographic_region_obligor", "geographic_region_collateral"])

    # Entity-derived regime values. The originator's identity is captured once,
    # on the entity, and reaches the regime defaults from there — an operator is
    # never asked for the same legal name twice.
    originators = case.entities_with_role("originator")
    if originators and "esma_annex2" in products:
        entity = originators[0]
        for key, dotted in (("legal_name", "defaults.originator_name"),
                            ("lei", "defaults.originator_legal_entity_identifier"),
                            ("country_of_establishment",
                             "defaults.originator_establishment_country")):
            value = entity.get(key)
            if _present(value) and not _present(_deep_get(doc, dotted)):
                _deep_set(doc, dotted, str(value).strip()
                          if key == "legal_name" else str(value).strip().upper())
        notes.append(f"Originator details from {entity.get('legal_name', '')}.")

    parties = _reporting_parties(case)
    if parties:
        doc["reporting_parties"] = parties
        notes.append("Standing reporting parties.")
    return doc, notes


def _reporting_parties(case: OnboardingCase) -> Dict[str, Any]:
    """Entities whose role has no regime field but which reports name.

    Written under one clearly-labelled block rather than scattered, and only for
    roles actually assigned.
    """
    wanted = ("trustee", "warehouse_lender", "servicer", "sponsor", "sspe",
              "investment_manager", "calculation_agent")
    out: Dict[str, Any] = {}
    for role in wanted:
        entities = case.entities_with_role(role)
        if not entities:
            continue
        out[role] = [{"legal_name": e.get("legal_name", ""),
                      **({"lei": e["lei"]} if e.get("lei") else {})}
                     for e in entities]
    return out


# --------------------------------------------------------------------------- #
# Investor reporting overlay
# --------------------------------------------------------------------------- #

def render_annex12_config(case: OnboardingCase, *,
                          cat: Optional[Catalogue] = None,
                          base: Optional[Dict[str, Any]] = None
                          ) -> Tuple[Dict[str, Any], List[str]]:
    cat = cat or catalogue()
    doc = copy.deepcopy(base) if base else {}
    annex12 = doc.setdefault("annex12", {})
    annex12.setdefault("meta", {}).setdefault(
        "template", "ESMA Annex 12 (Investor Report)")
    client = case.answers.get("client") or {}
    annex12.setdefault("assumptions", {})["reporting_currency"] = str(
        client.get("reporting_currency") or "").upper()

    written = 0
    for f, dotted, value in _route(cat, case, ARTEFACT_ANNEX12_CONFIG):
        _deep_set(doc, dotted, _coerce(f, value))
        written += 1

    # The reporting entity names itself; the projector otherwise falls back to
    # the master configuration.
    reporting = case.entities_with_role("reporting_entity")
    if reporting:
        deal = annex12.setdefault("deal", {})
        deal.setdefault("IVSS3", reporting[0].get("legal_name", ""))
        deal.setdefault("IVSS4", reporting[0].get("legal_name", ""))
        if reporting[0].get("lei"):
            deal.setdefault("IVSS1", reporting[0]["lei"])
    notes = ([f"{written} standing investor-report field"
              f"{'s' if written != 1 else ''}."] if written else [])
    return doc, notes


# --------------------------------------------------------------------------- #
# Portfolio metadata
# --------------------------------------------------------------------------- #

def render_portfolio_registry(case: OnboardingCase, *,
                              cat: Optional[Catalogue] = None,
                              base: Optional[Dict[str, Any]] = None
                              ) -> Tuple[Dict[str, Any], List[str]]:
    cat = cat or catalogue()
    section = cat.section("portfolios")
    doc = copy.deepcopy(base) if base else {}
    client_id = str((case.answers.get("client") or {}).get("client_id") or "")
    block = doc.setdefault("clients", {}).setdefault(client_id, {})
    existing = {str(e.get("source_portfolio_id")): e
                for e in (block.get("portfolios") or [])
                if isinstance(e, dict)}

    entries: List[Dict[str, Any]] = []
    for item in case.items("portfolios"):
        pid = str(item.get("portfolio_id") or "")
        entry = dict(existing.get(pid) or {})
        for f in (section.fields if section else []):
            if not str(f.writes_to).startswith(f"{ARTEFACT_PORTFOLIO_REGISTRY}:"):
                continue
            value = item.get(f.key)
            if _present(value):
                entry[f.writes_to.split(":", 1)[1]] = _coerce(f, value)
        # The owning entity is stored by name as well as reference, so the file
        # is readable without resolving into the onboarding record.
        entity = case.entity(str(item.get("owning_entity") or ""))
        if entity:
            entry["owning_entity_name"] = entity.get("legal_name", "")
        entry["pipeline_data_available"] = any(
            s.get("portfolio_id") == pid and s.get("dataset") == "pipeline"
            for s in case.items("sources"))
        # forecast_treatment is set only where onboarding actually knows: a
        # runoff curve is a governed input Trakt consumes, never one it invents.
        if entry.get("originates"):
            entry["forecast_treatment"] = "origination"
        elif entry.get("runoff_curve"):
            entry["forecast_treatment"] = "runoff"
        entries.append(entry)

    block["portfolios"] = entries
    return doc, [f"{len(entries)} portfolio"
                 f"{'s' if len(entries) != 1 else ''} described."]


# --------------------------------------------------------------------------- #
# Client index (tenancy)
# --------------------------------------------------------------------------- #

def render_client_index(case: OnboardingCase) -> Tuple[Dict[str, Any], List[str]]:
    """The tenant record: display name, default portfolio and the books this
    client may read. Same shape as ``config/tenancy.yaml``, written per client
    so onboarding never rewrites another tenant's entry."""
    client = case.answers.get("client") or {}
    client_id = str(client.get("client_id") or "")
    portfolios = [str(p.get("portfolio_id") or "")
                  for p in case.items("portfolios") if p.get("portfolio_id")]
    doc = {"tenants": {client_id: {
        "display_name": client.get("client_name", ""),
        "default_portfolio": client_id,
        "portfolios": [client_id, *portfolios],
    }}}
    return doc, [f"{client_id} may read {len(portfolios)} portfolio"
                 f"{'s' if len(portfolios) != 1 else ''}."]


# --------------------------------------------------------------------------- #
# Source registrations
# --------------------------------------------------------------------------- #

def render_source_records(case: OnboardingCase, *,
                          cat: Optional[Catalogue] = None,
                          registry: Optional[SourceRegistry] = None
                          ) -> Tuple[List[SourceRecord], List[str]]:
    """One record per portfolio and dataset.

    A record that already exists keeps everything a real delivery earned it —
    approved mapping, pinned schema fingerprint, role schemas, last-successful
    markers — and is never demoted from active. Onboarding owns the business
    facts; the registry owns the delivery evidence.
    """
    cat = cat or catalogue()
    section = cat.section("sources")
    client_id = str((case.answers.get("client") or {}).get("client_id") or "")
    out: List[SourceRecord] = []
    notes: List[str] = []

    for item in case.items("sources"):
        pid = str(item.get("portfolio_id") or "")
        dataset = str(item.get("dataset") or "funded")
        cadence = str(item.get("cadence") or "monthly")
        portfolio = case.portfolio(pid)
        existing = (registry.lookup(client_id, pid, dataset, cadence)
                    if registry is not None else None)

        record = SourceRecord(
            client_id=client_id, source_portfolio_id=pid, dataset=dataset,
            frequency=cadence,
            source_portfolio_type=(str(portfolio.get("portfolio_type"))
                                   if portfolio else None),
            source_system=str(item.get("source_party") or "") or None,
            regime_required=bool(item.get("regime_required")),
            expected_columns=_lines(item.get("expected_files")),
            status=(STATUS_ACTIVE if item.get("mapping_complete")
                    else STATUS_PENDING_REVIEW),
        )
        for f in (section.fields if section else []):
            target = str(f.writes_to)
            if not target.startswith(f"{ARTEFACT_SOURCE_REGISTRY}:"):
                continue
            attr = target.split(":", 1)[1]
            value = item.get(f.key)
            if _present(value) and hasattr(record, attr) \
                    and attr not in ("expected_columns",):
                setattr(record, attr, _coerce(f, value))

        if existing is not None:
            record.approved_mapping_id = existing.approved_mapping_id
            record.mapping_config_path = existing.mapping_config_path
            record.mapping_version = existing.mapping_version
            record.expected_schema_fingerprint = existing.expected_schema_fingerprint
            record.file_role_schemas = dict(existing.file_role_schemas)
            record.file_role_aliases = dict(existing.file_role_aliases)
            record.last_successful_run_id = existing.last_successful_run_id
            record.last_successful_reporting_period = \
                existing.last_successful_reporting_period
            record.expected_columns = (record.expected_columns
                                       or list(existing.expected_columns))
            if existing.status == STATUS_ACTIVE and existing.has_approved_mapping:
                record.status = STATUS_ACTIVE
            notes.append(f"{record.key} updated; approved mapping kept.")
        else:
            notes.append(f"{record.key} registered, awaiting its first pack.")
        out.append(record)
    return out, notes


def _lines(value: Any) -> List[str]:
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    return [line.strip() for line in str(value or "").splitlines()
            if line.strip()]


# --------------------------------------------------------------------------- #
# Plan / apply
# --------------------------------------------------------------------------- #

def plan(case: OnboardingCase, *, store, cat: Optional[Catalogue] = None,
         registry=None) -> List[Artefact]:
    """Everything activation would write, with current content alongside.

    Writes nothing. ``store`` is an :class:`~.store.OnboardingStore`.
    """
    cat = cat or catalogue()
    client_id = str((case.answers.get("client") or {}).get("client_id") or "")
    base_documents = case.base_documents or {}
    artefacts: List[Artefact] = []

    def previous(rel: str) -> Optional[str]:
        return store.read_artefact(client_id, rel) if client_id else None

    def add(kind: str, rel: str, doc: Dict[str, Any], notes: List[str]) -> None:
        prev = previous(rel)
        text = _dump(doc)
        artefacts.append(Artefact(kind=kind, rel=rel,
                                  label=ARTEFACT_LABELS[kind],
                                  action=_action(prev, text), text=text,
                                  previous_text=prev or "", summary=notes))

    prev_client = previous(client_config_rel(client_id)) if client_id else None
    doc, notes = render_client_config(
        case, cat=cat,
        base=(_parse(prev_client) if prev_client
              else copy.deepcopy(base_documents.get(ARTEFACT_CLIENT_CONFIG) or {})))
    add(ARTEFACT_CLIENT_CONFIG, client_config_rel(client_id), doc, notes)

    if "investor_reporting" in case.products:
        rel = annex12_config_rel(client_id)
        prev = previous(rel)
        doc12, notes12 = render_annex12_config(
            case, cat=cat,
            base=(_parse(prev) if prev
                  else copy.deepcopy(
                      base_documents.get(ARTEFACT_ANNEX12_CONFIG) or {})))
        add(ARTEFACT_ANNEX12_CONFIG, rel, doc12, notes12)

    relp = portfolio_registry_rel(client_id)
    docp, notesp = render_portfolio_registry(case, cat=cat,
                                             base=_parse(previous(relp)))
    add(ARTEFACT_PORTFOLIO_REGISTRY, relp, docp, notesp)

    relt = tenancy_rel(client_id)
    doct, notest = render_client_index(case)
    add(ARTEFACT_TENANCY, relt, doct, notest)

    records, notesr = render_source_records(case, cat=cat, registry=registry)
    rows: List[Dict[str, Any]] = []
    for record in records:
        existing = (registry.lookup(client_id, record.source_portfolio_id,
                                    record.dataset, record.frequency)
                    if registry is not None else None)
        portfolio = case.portfolio(record.source_portfolio_id)
        rows.append({
            **record.to_dict(),
            "action": "update" if existing is not None else "create",
            "portfolio_label": (str(portfolio.get("display_name") or "")
                                if portfolio else ""),
            "expected_location": blob_prefix(
                client_id=client_id,
                portfolio_type=record.source_portfolio_type or "direct",
                dataset=record.dataset, cadence=record.frequency,
                portfolio_id=record.source_portfolio_id),
        })
    artefacts.append(Artefact(
        kind=ARTEFACT_SOURCE_REGISTRY, rel="source registrations",
        label=ARTEFACT_LABELS[ARTEFACT_SOURCE_REGISTRY],
        action=("update" if any(r["action"] == "update" for r in rows)
                else ("create" if rows else "unchanged")),
        records=rows, summary=notesr))
    return artefacts


def apply(case: OnboardingCase, *, store, version: int, registry=None,
          cat: Optional[Catalogue] = None,
          artefacts: Optional[List[Artefact]] = None) -> List[Dict[str, Any]]:
    """Write the planned artefacts. Called only on activation.

    Idempotent: an artefact whose content already matches is reported as
    unchanged and not rewritten, and a source record is upserted by its stable
    key, so re-activating an approved case converges rather than duplicating.
    """
    cat = cat or catalogue()
    artefacts = artefacts or plan(case, store=store, cat=cat, registry=registry)
    client_id = str((case.answers.get("client") or {}).get("client_id") or "")
    written: List[Dict[str, Any]] = []

    for artefact in artefacts:
        if artefact.kind == ARTEFACT_SOURCE_REGISTRY:
            keys: List[str] = []
            if registry is not None:
                records, _ = render_source_records(case, cat=cat,
                                                   registry=registry)
                for record in records:
                    registry.upsert(record)
                    keys.append(record.key)
            written.append({"kind": artefact.kind,
                            "target": "source registrations",
                            "action": artefact.action,
                            "detail": {"records": keys}})
            continue
        if artefact.action == "unchanged":
            written.append({"kind": artefact.kind, "target": artefact.rel,
                            "action": "unchanged", "detail": {}})
            continue
        uri = store.write_artefact(client_id, version, artefact.rel,
                                   artefact.text)
        written.append({"kind": artefact.kind, "target": artefact.rel,
                        "action": artefact.action, "detail": {"uri": uri}})
    return written


def unrepresented(case: OnboardingCase,
                  cat: Optional[Catalogue] = None) -> List[Dict[str, Any]]:
    """Standing information collected but with no artefact to land in.

    Two populations: fields the catalogue routes to ``onboarding_record``, and
    the per-product declarations of what the regime model cannot hold. Both are
    shown at review so nothing is silently dropped.
    """
    cat = cat or catalogue()
    out: List[Dict[str, Any]] = []
    for section in cat.sections:
        for f in section.fields:
            if f.writes_to != ARTEFACT_ONBOARDING_RECORD or not f.collected:
                continue
            out.append({"key": f.key, "label": f.label,
                        "section": section.label,
                        "reason": "Held in the governed onboarding record. No "
                                  "existing configuration artefact represents "
                                  "it."})
    for key in case.products:
        product = (cat.regime_products or {}).get(key) or {}
        for entry in product.get("unrepresented") or []:
            out.append({"product": product.get("label", key), **entry})
    return out
