"""operations_control.onboarding.generation — profile -> governed artefacts.

The operator answers business questions; this module writes the technical
configuration. It generates the artefacts Trakt ALREADY reads, in their existing
formats:

  ``config/client/config_client_{CLIENT}.yaml``  the master client configuration
                                                 (engine/orchestrator/trakt_run.py
                                                 ``--master-config``,
                                                 operations_control.configuration.
                                                 resolver, annex2.preflight)
  ``config/client/config_client_annex12.yaml``   the investor-report overlay
                                                 (engine/gate_4_projection/
                                                 annex12_projector.py ``--config``)
  ``config/client/portfolio_registry.yaml``      per-portfolio business metadata
                                                 (mi_agent/portfolio_metadata.py)
  the durable source registry                    one record per client/portfolio/
                                                 dataset/frequency
                                                 (apps.blob_trigger_app.source_registry)

Generation is a MERGE, never a replacement. Blocks the wizard does not own —
``transformations``, ``enrichment``, ``pipeline_persistence``, ``loan_engine``,
anything an administrator has added — are carried through from the current
document untouched. A plan is produced first (:func:`plan`), shown to the
operator, and only written on approval (:func:`apply`).
"""

from __future__ import annotations

import copy
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

from apps.blob_trigger_app.source_registry import (
    STATUS_ACTIVE,
    SourceRecord,
    SourceRegistry,
)

from ..configuration.packages import ASSET_MODEL
from .model import (
    ClientOnboardingProfile,
    PortfolioStanding,
    blob_prefix,
    standing_field_spec,
)

REPO = Path(__file__).resolve().parents[2]

#: Seed documents. Used only to inherit blocks onboarding does not own when a
#: client has no generated configuration yet.
SEED_CLIENT_CONFIG = REPO / "config/client/config_client_ERM_UK.yaml"
SEED_ANNEX12_CONFIG = REPO / "config/client/config_client_annex12.yaml"

GENERATED_BANNER = (
    "# GENERATED by the Trakt Operations Control Centre — Client Onboarding.\n"
    "# This file is a governed artefact. Change it through Client Onboarding,\n"
    "# not by hand: a hand edit is not versioned, not attributed and not\n"
    "# audited, and the next approved change will overwrite it.\n"
)

ARTEFACT_CLIENT_CONFIG = "client_config"
ARTEFACT_ANNEX12_CONFIG = "annex12_config"
ARTEFACT_PORTFOLIO_REGISTRY = "portfolio_registry"
ARTEFACT_SOURCE_REGISTRY = "source_registry"


def client_config_rel(client_id: str) -> str:
    return f"config/client/config_client_{client_id}.yaml"


def annex12_config_rel(client_id: str) -> str:
    return f"config/client/config_client_{client_id}_annex12.yaml"


def portfolio_registry_rel(client_id: str) -> str:
    return f"config/client/portfolio_registry_{client_id}.yaml"


@dataclass
class Artefact:
    """One governed document (or registry) the approval will write."""

    kind: str
    rel: str                       # repository-relative path, or a registry name
    label: str                     # operator wording
    action: str                    # create | update | unchanged
    text: str = ""                 # rendered document (YAML artefacts)
    previous_text: str = ""
    #: For the source registry: the records that will be written.
    records: List[Dict[str, Any]] = field(default_factory=list)
    #: Plain-English summary of what changes.
    summary: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def _deep_set(node: Dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    for part in parts[:-1]:
        nxt = node.get(part)
        if not isinstance(nxt, dict):
            nxt = {}
            node[part] = nxt
        node = nxt
    node[parts[-1]] = value


def _deep_get(node: Any, dotted: str) -> Any:
    for part in dotted.split("."):
        if not isinstance(node, dict):
            return None
        node = node.get(part)
    return node


def _dump(doc: Dict[str, Any]) -> str:
    return GENERATED_BANNER + yaml.safe_dump(doc, sort_keys=False,
                                             allow_unicode=True)


def _parse(text: Optional[str]) -> Dict[str, Any]:
    if not text:
        return {}
    try:
        return yaml.safe_load(text) or {}
    except yaml.YAMLError:
        return {}


def _seed(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return {}


def _yes(value: Any) -> bool:
    return str(value).strip().lower() in ("y", "yes", "true", "1")


# --------------------------------------------------------------------------- #
# Client configuration
# --------------------------------------------------------------------------- #

def render_client_config(profile: ClientOnboardingProfile,
                         *, base: Optional[Dict[str, Any]] = None,
                         spec: Optional[Dict[str, Any]] = None
                         ) -> Tuple[Dict[str, Any], List[str]]:
    """The master client configuration, in its existing shape.

    Only the blocks onboarding owns are written; everything else in ``base``
    survives. Returns the document and a plain-English change summary.
    """
    spec = spec or standing_field_spec()
    doc = copy.deepcopy(base) if base else {}
    notes: List[str] = []
    c = profile.client

    # -- client identity (existing `client:` block) ------------------------- #
    client_block = doc.setdefault("client", {})
    client_block["client_id"] = c.client_id
    client_block["display_name"] = c.client_name
    client_block["environment"] = c.environment or "production"
    client_block["legal_entity_name"] = c.legal_entity_name
    client_block["time_zone"] = c.time_zone
    client_block["reporting_contact"] = {
        "name": c.primary_reporting_contact, "email": c.reporting_email}
    client_block["operational_contact"] = {
        "name": c.operational_contact, "email": c.operational_email}
    notes.append(f"Client identity for {c.client_name}.")

    # -- portfolio defaults (existing `portfolio:` block) ------------------- #
    # The legacy block is single-valued: it describes the client's dominant
    # book. Multi-portfolio detail lives in the portfolio registry, so this
    # block is populated from the first portfolio and stays compatible with
    # every existing reader.
    portfolio_block = doc.setdefault("portfolio", {})
    if profile.portfolios:
        first = profile.portfolios[0]
        portfolio_block["asset_class"] = first.asset_class
    portfolio_block["country"] = (c.jurisdiction or "").upper()
    portfolio_block["base_currency"] = (c.reporting_currency or "").upper()
    notes.append("Portfolio jurisdiction and reporting currency.")

    # -- regimes (existing default_regime / supported_regimes / regime) ----- #
    supported: List[str] = []
    for p in profile.portfolios:
        for regime in (ASSET_MODEL.get(p.asset_class, {})
                       .get("supports_regimes") or []):
            if regime not in supported:
                supported.append(regime)
    if "investor_reporting" in profile.reporting.products:
        annex12 = (spec.get("products", {}).get("investor_reporting", {})
                   .get("regime_id") or "ESMA_Annex12")
        if annex12 not in supported:
            supported.append(annex12)
    if supported:
        doc["supported_regimes"] = supported
        chosen = ("ESMA_Annex2"
                  if "esma_annex2" in profile.reporting.products
                  and "ESMA_Annex2" in supported else supported[0])
        doc["default_regime"] = chosen
        # Retained for backward compatibility, exactly as the legacy file does.
        doc["regime"] = chosen
        notes.append("Regime capability set: " + ", ".join(supported) + ".")

    # -- pipeline switches (existing `pipeline:` block) --------------------- #
    pipeline = doc.setdefault("pipeline", {})
    pipeline.setdefault("loan_engine_enabled", False)
    pipeline["mi_enabled"] = True
    pipeline["esma_enabled"] = "esma_annex2" in profile.reporting.products
    notes.append("Reporting products: "
                 + (", ".join(sorted(profile.reporting.products)) or "MI only")
                 + ".")

    # -- regime answers routed by the governed spec ------------------------- #
    for product_key, answers in (profile.regime or {}).items():
        product = (spec.get("products") or {}).get(product_key) or {}
        for f in product.get("fields") or []:
            target = str(f.get("writes_to") or "")
            if not target.startswith(f"{ARTEFACT_CLIENT_CONFIG}:"):
                continue
            value = answers.get(f.get("key"))
            if value is None or not str(value).strip():
                continue
            dotted = target.split(":", 1)[1]
            if f.get("format") == "boolean":
                value = _yes(value)
            elif f.get("format") == "country":
                value = str(value).strip().upper()
            elif f.get("format") == "lei":
                value = str(value).strip().upper()
            else:
                value = str(value).strip()
            _deep_set(doc, dotted, value)
    if profile.regime.get("esma_annex2"):
        notes.append("Annex 2 standing values injected into every reported row.")

    # The UK geography override carries a governed shape, not just a flag: when
    # switched on it must name the value and the fields it applies to, exactly
    # as the legacy configuration does.
    if _deep_get(doc, "regime_overrides.ESMA_Annex2.uk_geography.enabled"):
        _deep_set(doc, "regime_overrides.ESMA_Annex2.uk_geography.override_value",
                  "GBZZZ")
        _deep_set(doc,
                  "regime_overrides.ESMA_Annex2.uk_geography.target_fields",
                  ["geographic_region_obligor", "geographic_region_collateral"])

    # -- static reporting: branding + conventions --------------------------- #
    sr = profile.static_reporting
    if sr.app_title or sr.primary_color or sr.logo_uri or sr.disclaimer:
        mi = doc.setdefault("mi", {})
        branding = mi.setdefault("branding", {})
        if sr.app_title:
            branding["app_title"] = sr.app_title
        if sr.primary_color:
            branding.setdefault("theme", {})["primary_color"] = sr.primary_color
        if sr.logo_uri:
            branding["logo_uri"] = sr.logo_uri
        if sr.disclaimer:
            branding["disclaimer"] = sr.disclaimer
        notes.append("Report branding.")
    if sr.day_count_convention or sr.payment_convention:
        engine = doc.setdefault("loan_engine", {})
        if sr.day_count_convention:
            engine["day_count_convention"] = sr.day_count_convention
        if sr.payment_convention:
            engine["interest_payment_frequency"] = sr.payment_convention
        notes.append("Calculation conventions.")

    # -- reporting parties (no regime home; kept with the client) ----------- #
    parties = {k: v for k, v in (
        ("investor_contact", sr.investor_contact),
        ("investor_email", sr.investor_email),
        ("trustee_name", sr.trustee_name),
        ("warehouse_lender", sr.warehouse_lender),
        ("reporting_convention", sr.reporting_convention),
    ) if str(v or "").strip()}
    if parties:
        doc["reporting_parties"] = parties
        notes.append("Standing reporting parties (trustee, investor contact, "
                     "warehouse lender).")
    return doc, notes


# --------------------------------------------------------------------------- #
# Investor reporting overlay
# --------------------------------------------------------------------------- #

def render_annex12_config(profile: ClientOnboardingProfile,
                          *, base: Optional[Dict[str, Any]] = None,
                          spec: Optional[Dict[str, Any]] = None
                          ) -> Tuple[Dict[str, Any], List[str]]:
    """The Annex 12 client instance overlay.

    The projector deep-merges template -> asset overlay -> this document, and
    resolves IVSS1/IVSS3/IVSS4 from the master configuration when they are
    absent. Deal-structure blocks already present (triggers, cashflows) are
    carried through untouched — they are not standing client information.
    """
    spec = spec or standing_field_spec()
    doc = copy.deepcopy(base) if base else {}
    notes: List[str] = []
    annex12 = doc.setdefault("annex12", {})
    meta = annex12.setdefault("meta", {})
    meta.setdefault("template", "ESMA Annex 12 (Investor Report)")
    annex12.setdefault("assumptions", {})["reporting_currency"] = (
        profile.client.reporting_currency or "").upper()

    product = (spec.get("products") or {}).get("investor_reporting") or {}
    written = 0
    for f in product.get("fields") or []:
        target = str(f.get("writes_to") or "")
        if not target.startswith(f"{ARTEFACT_ANNEX12_CONFIG}:"):
            continue
        value = (profile.regime.get("investor_reporting") or {}).get(f.get("key"))
        if value is None or not str(value).strip():
            continue
        _deep_set(doc, target.split(":", 1)[1], str(value).strip())
        written += 1
    if written:
        notes.append(f"{written} standing investor-report field"
                     f"{'s' if written != 1 else ''}.")
    if profile.client.legal_entity_name:
        deal = annex12.setdefault("deal", {})
        deal.setdefault("IVSS3", profile.client.legal_entity_name)
        deal.setdefault("IVSS4", profile.client.legal_entity_name)
    return doc, notes


# --------------------------------------------------------------------------- #
# Portfolio registry
# --------------------------------------------------------------------------- #

def _originates(p: PortfolioStanding) -> bool:
    """The governed default: direct books originate, acquired books do not —
    unless onboarding was told otherwise (portfolio_registry.example.yaml)."""
    if p.originates is not None:
        return bool(p.originates)
    return p.portfolio_type == "direct"


def render_portfolio_registry(profile: ClientOnboardingProfile,
                              *, base: Optional[Dict[str, Any]] = None
                              ) -> Tuple[Dict[str, Any], List[str]]:
    """Per-portfolio business metadata, in the per-client shape the resolver
    already supports (``clients: {<id>: {portfolios: [...]}}``)."""
    doc = copy.deepcopy(base) if base else {}
    clients = doc.setdefault("clients", {})
    block = clients.setdefault(profile.client_id, {})
    entries: List[Dict[str, Any]] = []
    existing = {str(e.get("source_portfolio_id")): e
                for e in (block.get("portfolios") or [])
                if isinstance(e, dict)}
    for p in profile.portfolios:
        entry = dict(existing.get(p.portfolio_id) or {})
        entry.update({
            "source_portfolio_id": p.portfolio_id,
            "source_portfolio_type": p.portfolio_type,
            "source_portfolio_label": p.display_name,
            "originates": _originates(p),
            "pipeline_data_available": p.has_pipeline,
        })
        # forecast_treatment is only set where onboarding actually knows: a
        # supplied runoff curve is a governed input Trakt consumes, never one
        # it generates, so an acquired book without one is left to the
        # platform's hold-constant default rather than given a treatment here.
        if _originates(p):
            entry["forecast_treatment"] = "origination"
        elif entry.get("runoff_curve"):
            entry["forecast_treatment"] = "runoff"
        entries.append(entry)
    block["portfolios"] = entries
    return doc, [f"{len(entries)} portfolio"
                 f"{'s' if len(entries) != 1 else ''} described."]


# --------------------------------------------------------------------------- #
# Source registry
# --------------------------------------------------------------------------- #

def render_source_records(profile: ClientOnboardingProfile,
                          *, registry: Optional[SourceRegistry] = None
                          ) -> Tuple[List[SourceRecord], List[str]]:
    """The source registry records a profile implies.

    An EXISTING record is preserved and only extended: its approved mapping,
    pinned schema fingerprint, role schemas and last-successful markers are
    never cleared by onboarding — those are earned by a real delivery, and
    resetting them would send a recognised recurring pack back through source
    onboarding. Onboarding owns the business facts (source system, cadence,
    regime scope); the registry owns the delivery evidence.
    """
    out: List[SourceRecord] = []
    notes: List[str] = []
    for s in profile.sources:
        portfolio = profile.portfolio(s.portfolio_id)
        existing = (registry.lookup(profile.client_id, s.portfolio_id,
                                    s.dataset, s.frequency)
                    if registry is not None else None)
        record = SourceRecord(
            client_id=profile.client_id,
            source_portfolio_id=s.portfolio_id,
            dataset=s.dataset,
            frequency=s.frequency,
            source_portfolio_type=(portfolio.portfolio_type
                                   if portfolio else None),
            source_system=s.source_system or (portfolio.source_system
                                              if portfolio else "") or None,
            regime_required=bool(s.regime_required),
            expected_columns=list(s.expected_files),
            status=s.status,
        )
        if existing is not None:
            record.approved_mapping_id = existing.approved_mapping_id
            record.mapping_config_path = existing.mapping_config_path
            record.mapping_version = existing.mapping_version
            record.expected_schema_fingerprint = existing.expected_schema_fingerprint
            record.file_role_schemas = dict(existing.file_role_schemas)
            record.file_role_aliases = dict(existing.file_role_aliases)
            record.last_successful_run_id = existing.last_successful_run_id
            record.last_successful_reporting_period = \
                existing.last_successful_reporting_period
            record.expected_columns = (list(s.expected_files)
                                       or list(existing.expected_columns))
            # A source already proven by a delivery stays active; onboarding
            # never demotes it back to pending review.
            if existing.status == STATUS_ACTIVE and existing.has_approved_mapping:
                record.status = STATUS_ACTIVE
            notes.append(f"{record.key} updated (approved mapping preserved).")
        else:
            notes.append(f"{record.key} registered, awaiting its first pack.")
        out.append(record)
    return out, notes


# --------------------------------------------------------------------------- #
# Plan / apply
# --------------------------------------------------------------------------- #

def plan(profile: ClientOnboardingProfile, *, store, registry=None,
         spec: Optional[Dict[str, Any]] = None,
         base_documents: Optional[Dict[str, Dict[str, Any]]] = None
         ) -> List[Artefact]:
    """Everything approval would write, with the current content alongside.

    Nothing is written. ``store`` is an :class:`~.store.OnboardingStore`.

    ``base_documents`` carries the legacy documents a MIGRATED client is being
    adopted from (``{kind: parsed yaml}``), so blocks onboarding does not own —
    enrichment, transformations, persistence, deal-structure triggers — survive
    adoption intact. A genuinely new client supplies none, and starts clean:
    inheriting another client's enrichment rules would be exactly the silent
    coupling this capability exists to remove.
    """
    spec = spec or standing_field_spec()
    base_documents = base_documents or {}
    client_id = profile.client_id
    artefacts: List[Artefact] = []

    # -- client configuration ---------------------------------------------- #
    rel = client_config_rel(client_id)
    previous = store.read_artefact(client_id, rel)
    base = (_parse(previous) if previous
            else copy.deepcopy(base_documents.get(ARTEFACT_CLIENT_CONFIG) or {}))
    doc, notes = render_client_config(profile, base=base, spec=spec)
    text = _dump(doc)
    artefacts.append(Artefact(
        kind=ARTEFACT_CLIENT_CONFIG, rel=rel, label="Client configuration",
        action=_action(previous, text), text=text,
        previous_text=previous or "", summary=notes))

    # -- investor reporting overlay ---------------------------------------- #
    if "investor_reporting" in profile.reporting.products:
        rel12 = annex12_config_rel(client_id)
        previous12 = store.read_artefact(client_id, rel12)
        base12 = (_parse(previous12) if previous12
                  else copy.deepcopy(
                      base_documents.get(ARTEFACT_ANNEX12_CONFIG) or {}))
        doc12, notes12 = render_annex12_config(profile, base=base12, spec=spec)
        text12 = _dump(doc12)
        artefacts.append(Artefact(
            kind=ARTEFACT_ANNEX12_CONFIG, rel=rel12,
            label="Investor report configuration",
            action=_action(previous12, text12), text=text12,
            previous_text=previous12 or "", summary=notes12))

    # -- portfolio registry ------------------------------------------------- #
    relp = portfolio_registry_rel(client_id)
    previousp = store.read_artefact(client_id, relp)
    docp, notesp = render_portfolio_registry(profile, base=_parse(previousp))
    textp = _dump(docp)
    artefacts.append(Artefact(
        kind=ARTEFACT_PORTFOLIO_REGISTRY, rel=relp, label="Portfolio metadata",
        action=_action(previousp, textp), text=textp,
        previous_text=previousp or "", summary=notesp))

    # -- source registry ---------------------------------------------------- #
    records, notesr = render_source_records(profile, registry=registry)
    rows: List[Dict[str, Any]] = []
    for record in records:
        existing = (registry.lookup(client_id, record.source_portfolio_id,
                                    record.dataset, record.frequency)
                    if registry is not None else None)
        portfolio = profile.portfolio(record.source_portfolio_id)
        rows.append({
            **record.to_dict(),
            "action": "update" if existing is not None else "create",
            "expected_location": blob_prefix(
                client_id, record.source_portfolio_type or "direct",
                record.dataset, record.frequency, record.source_portfolio_id),
            "portfolio_label": (portfolio.display_name if portfolio else ""),
        })
    artefacts.append(Artefact(
        kind=ARTEFACT_SOURCE_REGISTRY, rel="source registry",
        label="Source registrations",
        action=("update" if any(r["action"] == "update" for r in rows)
                else ("create" if rows else "unchanged")),
        records=rows, summary=notesr))
    return artefacts


def _action(previous: Optional[str], text: str) -> str:
    if previous is None:
        return "create"
    return "unchanged" if previous == text else "update"


def apply(profile: ClientOnboardingProfile, *, store, version: int,
          registry=None, artefacts: Optional[List[Artefact]] = None,
          base_documents: Optional[Dict[str, Dict[str, Any]]] = None
          ) -> List[Dict[str, Any]]:
    """Write the planned artefacts. Called only after operator approval."""
    artefacts = artefacts or plan(profile, store=store, registry=registry,
                                  base_documents=base_documents)
    written: List[Dict[str, Any]] = []
    for artefact in artefacts:
        if artefact.kind == ARTEFACT_SOURCE_REGISTRY:
            if registry is not None:
                records, _ = render_source_records(profile, registry=registry)
                for record in records:
                    registry.upsert(record)
            written.append({"kind": artefact.kind, "target": "source registry",
                            "action": artefact.action,
                            "detail": {"records": [r.get("client_id", "")
                                                   and f"{r['client_id']}/"
                                                   f"{r['source_portfolio_id']}/"
                                                   f"{r['dataset']}/"
                                                   f"{r['frequency']}"
                                                   for r in artefact.records]}})
            continue
        if artefact.action == "unchanged":
            written.append({"kind": artefact.kind, "target": artefact.rel,
                            "action": "unchanged", "detail": {}})
            continue
        uri = store.write_artefact(profile.client_id, version, artefact.rel,
                                   artefact.text)
        written.append({"kind": artefact.kind, "target": artefact.rel,
                        "action": artefact.action, "detail": {"uri": uri}})
    return written
