#!/usr/bin/env python3
"""Regenerate the approved onboarding-contract alias overlays.

    python -m simulation.tools.build_alias_contracts

Writes ``simulation/aliases/<asset_class>/aliases_client_contract.yaml`` from
:mod:`simulation.dialects.vocabulary`. The generated files are COMMITTED and are
what Gate 1 layers with ``--extra-aliases-dir``; regenerating them is a
deliberate act, exactly as approving a new onboarding contract would be.

``tests/test_simulation_dialects.py`` fails if a committed contract and the
vocabulary have drifted, so a dialect can never quietly rely on an alias no
contract approves.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

import yaml

from ..dialects.vocabulary import all_aliases
from ..models import ASSET_CLASSES

ALIASES_ROOT = Path(__file__).resolve().parents[1] / "aliases"

_HEADER = """\
# Approved onboarding contract — {asset_class} alias overlay
# =========================================================
#
# GENERATED by `python -m simulation.tools.build_alias_contracts` from
# simulation/dialects/vocabulary.py. Do not hand-edit: change the vocabulary and
# regenerate, so the source files a dialect writes and the contract that
# resolves them can never disagree.
#
# These are the SIMULATED lender's own source-header vocabularies (a UK lender
# export and a continental servicer export) resolved to the Trakt canonical
# model. They are layered on top of the global alias files at Gate 1 via
# `--extra-aliases-dir` and are scoped to this asset class only — the global
# mapper is deliberately left untouched, exactly as a real client's approved
# onboarding contract would be.
"""


def contract_for(asset_class: str) -> Dict[str, Dict[str, list]]:
    return {field: {"aliases": list(aliases)}
            for field, aliases in sorted(all_aliases(asset_class).items())}


def write_all(root: Path = ALIASES_ROOT) -> Dict[str, Path]:
    out: Dict[str, Path] = {}
    for asset_class in ASSET_CLASSES:
        path = root / asset_class / "aliases_client_contract.yaml"
        path.parent.mkdir(parents=True, exist_ok=True)
        body = yaml.safe_dump(contract_for(asset_class), sort_keys=True,
                              default_flow_style=False, allow_unicode=True)
        path.write_text(_HEADER.format(asset_class=asset_class) + "\n" + body,
                        encoding="utf-8")
        out[asset_class] = path
    return out


def main() -> int:  # pragma: no cover - developer entry point
    for asset_class, path in write_all().items():
        print(f"wrote {asset_class}: {path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
