"""apps.blob_trigger_app.deck_backfill — promote already-generated investor decks.

Decks generated by orchestration runs that completed BEFORE durable publication
was wired (or during a window where publication was disabled or failing) still
exist as immutable run artifacts:

    processed-v2/out/_blob_trigger/{orchestration_run}/reports/investor_pack.pptx

but were never promoted to the governed durable locations the MI API and the
Copilot action read:

    processed-v2/decks/{client}/{reporting_period}/investor_pack.pptx
    processed-v2/decks/{client}/latest/investor_pack.pptx
    processed-v2/decks/{client}/latest/latest_investor_pack.json

This is the explicit, one-time (and re-runnable) admin operation that closes that
gap. It is deliberately NOT wired into request handling: the Copilot action must
never scan orchestration output on a user request. Durable publication remains
the single source of truth for artifact discovery.

Guarantees
----------
* **Governed selection** — only runs whose ``run_state.json`` reports a completed
  orchestration AND whose investor-pack artifact is ``available`` are considered.
  Halted, failed, running and manifest-less run directories are skipped.
* **Validated** — each artifact must be a non-empty OOXML file; a checksum is
  computed and recorded on the pointer.
* **Idempotent** — the dated copy is write-once and the latest pointer never
  regresses to an older reporting period, so re-running is a no-op.
* **Dry-run** — ``--dry-run`` reports exactly what would be promoted and changes
  nothing.
* **Auditable** — every decision (promoted / skipped and why) is logged and
  returned.

Usage::

    python -m apps.blob_trigger_app.deck_backfill --dry-run
    python -m apps.blob_trigger_app.deck_backfill --client ERE
    python -m apps.blob_trigger_app.deck_backfill --run orun_ere_20260703T224438
"""

from __future__ import annotations

import argparse
import json
import logging
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from .layout import Layout
from .pptx_stage import (DECK_NAME_DEFAULT, deck_checksum, period_key,
                         persist_investor_deck, validate_deck_file)
from .storage import Storage, join_uri, open_storage

logger = logging.getLogger("trakt.blob_trigger.deck_backfill")

#: Where orchestration run directories are mirrored in the processed container.
#: Overridable so a deployment that parks run output elsewhere can still backfill.
DEFAULT_RUN_OUTPUT_REL = "out/_blob_trigger"
ENV_RUN_OUTPUT_ROOT = "TRAKT_RUN_OUTPUT_ROOT"

DECK_REL = f"reports/{DECK_NAME_DEFAULT}"
MANIFEST_NAME = "run_state.json"
ARTIFACT_KEY = "investor_pack_pptx"

#: Orchestration statuses that count as a governed, completed run.
_COMPLETED_STATUSES = {"done", "completed", "succeeded", "success"}


def run_output_root(layout: Layout, explicit: Optional[str] = None) -> str:
    """The URI prefix under which orchestration run directories live."""
    if explicit:
        return explicit.rstrip("/")
    import os
    env = os.environ.get(ENV_RUN_OUTPUT_ROOT)
    if env:
        return env.rstrip("/")
    return layout._processed(*DEFAULT_RUN_OUTPUT_REL.split("/"))


@dataclass
class DeckCandidate:
    """One ``reports/investor_pack.pptx`` found under the run-output root."""

    orchestration_run_id: str
    deck_uri: str
    manifest_uri: str
    client_id: Optional[str] = None
    reporting_period: Optional[str] = None
    source_run_id: Optional[str] = None
    eligible: bool = False
    reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "orchestration_run_id": self.orchestration_run_id,
            "deck_uri": self.deck_uri,
            "client_id": self.client_id,
            "reporting_period": self.reporting_period,
            "source_run_id": self.source_run_id,
            "eligible": self.eligible,
            "reason": self.reason,
        }


# --------------------------------------------------------------------------- #
# Discovery
# --------------------------------------------------------------------------- #
def _read_json(storage: Storage, uri: str) -> Optional[Dict[str, Any]]:
    try:
        if not storage.exists(uri):
            return None
        data = json.loads(storage.read_text(uri))
        return data if isinstance(data, dict) else None
    except Exception as exc:  # noqa: BLE001 — an unreadable manifest is "absent"
        logger.warning("deck backfill: unreadable manifest %s: %s", uri, exc)
        return None


def _classify(manifest: Optional[Dict[str, Any]],
              candidate: DeckCandidate) -> DeckCandidate:
    """Apply the governed-selection rules to one candidate (never raises)."""
    if manifest is None:
        candidate.reason = "no run_state.json — not a governed orchestration run"
        return candidate

    status = str(manifest.get("status") or "").strip().lower()
    if status not in _COMPLETED_STATUSES:
        candidate.reason = f"run status is '{status or 'unknown'}', not a completed run"
        return candidate
    if manifest.get("blockers"):
        candidate.reason = "run has unresolved blockers"
        return candidate

    artifact = (manifest.get("artifacts") or {}).get(ARTIFACT_KEY) or {}
    art_status = str(artifact.get("status") or "").strip().lower()
    # An artifact record is authoritative when present; a run that predates the
    # manifest artifact record is still eligible on the file's own merits.
    if art_status and art_status != "available":
        candidate.reason = f"investor pack artifact status is '{art_status}'"
        return candidate

    candidate.source_run_id = manifest.get("run_id") or None
    candidate.client_id = (artifact.get("client_id")
                           or manifest.get("client_id") or None)
    if not candidate.client_id:
        candidate.reason = "no client_id in the run manifest"
        return candidate

    published = artifact.get("published") or {}
    period = (published.get("period") or artifact.get("reporting_period")
              or manifest.get("reporting_period") or manifest.get("as_of_date"))
    candidate.reporting_period = period_key(str(period or "")) or None
    if not candidate.reporting_period:
        candidate.reason = ("no reporting period in the run manifest — supply "
                            "--period to promote this run explicitly")
        return candidate

    candidate.eligible = True
    return candidate


def discover_candidates(storage: Storage, root_uri: str,
                        *, client_id: Optional[str] = None,
                        run_id: Optional[str] = None) -> List[DeckCandidate]:
    """Every investor-pack artifact under *root_uri*, classified for promotion.

    Scanning is confined to the run-output root and is an ADMIN operation — it is
    never performed on a request path.
    """
    try:
        uris = storage.list(root_uri)
    except Exception as exc:  # noqa: BLE001 — an unreachable root yields nothing
        logger.warning("deck backfill: cannot list %s: %s", root_uri, exc)
        return []

    candidates: List[DeckCandidate] = []
    for uri in sorted(uris):
        if not uri.endswith("/" + DECK_REL):
            continue
        run_dir = uri[: -(len(DECK_REL) + 1)]
        orun = run_dir.rstrip("/").split("/")[-1]
        if run_id and orun != run_id:
            continue
        candidate = DeckCandidate(
            orchestration_run_id=orun, deck_uri=uri,
            manifest_uri=join_uri(run_dir, MANIFEST_NAME))
        _classify(_read_json(storage, candidate.manifest_uri), candidate)
        if client_id and candidate.client_id and candidate.client_id != client_id:
            continue
        candidates.append(candidate)
    return candidates


# --------------------------------------------------------------------------- #
# Promotion
# --------------------------------------------------------------------------- #
def _already_published(storage: Storage, layout: Layout,
                       candidate: DeckCandidate, checksum: str) -> bool:
    """True when the dated copy exists AND the latest pointer already describes
    exactly these bytes for this client — i.e. a re-run is a genuine no-op."""
    try:
        period_uri = layout.deck_period_uri(candidate.client_id or "",
                                            candidate.reporting_period or "")
        if not storage.exists(period_uri):
            return False
        ptr_uri = layout.deck_latest_pointer_uri(candidate.client_id or "")
        if not storage.exists(ptr_uri):
            return False
        ptr = json.loads(storage.read_text(ptr_uri)) or {}
        return ptr.get("checksum") == checksum
    except Exception:  # noqa: BLE001 — unknown state → let the publish decide
        return False


def promote(storage: Storage, layout: Layout, candidate: DeckCandidate,
            *, dry_run: bool = False) -> Dict[str, Any]:
    """Publish one candidate's deck. Returns an audit record (never raises)."""
    record: Dict[str, Any] = {**candidate.to_dict(), "action": "skipped"}
    if not candidate.eligible:
        return record

    with tempfile.TemporaryDirectory(prefix="trakt_deck_backfill_") as tmp:
        local = Path(tmp) / DECK_NAME_DEFAULT
        try:
            storage.download_file(candidate.deck_uri, local)
        except Exception as exc:  # noqa: BLE001
            record["reason"] = f"could not fetch the run artifact: {exc}"
            return record

        invalid = validate_deck_file(local)
        if invalid is not None:
            record["action"] = "rejected"
            record["reason"] = f"invalid artifact: {invalid}"
            return record
        checksum = deck_checksum(local)
        record["checksum"] = checksum

        if _already_published(storage, layout, candidate, checksum):
            record["action"] = "already_published"
            record["reason"] = "dated copy and latest pointer already match"
            return record

        if dry_run:
            record["action"] = "would_promote"
            record["reason"] = ""
            return record

        published = persist_investor_deck(
            local, client_id=candidate.client_id or "",
            period=candidate.reporting_period or "",
            orchestration_run_id=candidate.orchestration_run_id,
            source_run_id=candidate.source_run_id,
            force=True, log=logger)
        if published is None:
            record["reason"] = "durable publish failed (see logs)"
            return record
        record["action"] = "promoted"
        record["reason"] = ""
        record["published"] = published
        return record


@dataclass
class BackfillResult:
    root: str
    dry_run: bool
    records: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def promoted(self) -> List[Dict[str, Any]]:
        return [r for r in self.records
                if r["action"] in ("promoted", "would_promote")]

    @property
    def skipped(self) -> List[Dict[str, Any]]:
        return [r for r in self.records
                if r["action"] not in ("promoted", "would_promote")]

    def to_dict(self) -> Dict[str, Any]:
        return {"root": self.root, "dry_run": self.dry_run,
                "scanned": len(self.records), "promoted": len(self.promoted),
                "skipped": len(self.skipped), "records": self.records}


def run_backfill(*, storage: Optional[Storage] = None,
                 layout: Optional[Layout] = None,
                 root: Optional[str] = None,
                 client_id: Optional[str] = None,
                 run_id: Optional[str] = None,
                 period: Optional[str] = None,
                 dry_run: bool = False) -> BackfillResult:
    """Discover and promote un-published investor decks.

    ``period`` overrides the reporting period for candidates whose manifest does
    not carry one — an explicit operator decision, never inferred.
    """
    storage = storage or open_storage()
    layout = layout or Layout.from_env()
    root = run_output_root(layout, root)

    candidates = discover_candidates(storage, root, client_id=client_id,
                                     run_id=run_id)
    override = period_key(period or "") if period else None
    if override:
        for c in candidates:
            if not c.reporting_period and c.client_id:
                c.reporting_period = override
                c.eligible = True
                c.reason = ""

    # Oldest reporting period first, so the client's `latest` ends on the newest
    # valid period regardless of the order storage enumerated the runs in.
    candidates.sort(key=lambda c: (c.client_id or "", c.reporting_period or "",
                                   c.orchestration_run_id))

    result = BackfillResult(root=root, dry_run=dry_run)
    for candidate in candidates:
        record = promote(storage, layout, candidate, dry_run=dry_run)
        logger.info("deck backfill %s: run=%s client=%s period=%s (%s)",
                    record["action"], candidate.orchestration_run_id,
                    candidate.client_id, candidate.reporting_period,
                    record.get("reason") or "ok")
        result.records.append(record)
    return result


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m apps.blob_trigger_app.deck_backfill",
        description="Promote already-generated investor decks to the governed "
                    "durable deck locations.")
    ap.add_argument("--root", default=None,
                    help="Run-output root URI (default: the processed container's "
                         f"{DEFAULT_RUN_OUTPUT_REL}, or ${ENV_RUN_OUTPUT_ROOT}).")
    ap.add_argument("--client", default=None, help="Only this client id.")
    ap.add_argument("--run", default=None, help="Only this orchestration run id.")
    ap.add_argument("--period", default=None,
                    help="Reporting period (YYYY-MM) for runs whose manifest "
                         "does not record one. Applied only to those runs.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Report what would be promoted; change nothing.")
    ap.add_argument("--json", action="store_true", help="Emit the audit record as JSON.")
    args = ap.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    result = run_backfill(root=args.root, client_id=args.client, run_id=args.run,
                          period=args.period, dry_run=args.dry_run)
    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        verb = "would promote" if args.dry_run else "promoted"
        print(f"Scanned {len(result.records)} run artifact(s) under {result.root}: "
              f"{verb} {len(result.promoted)}, skipped {len(result.skipped)}.")
        for r in result.records:
            print(f"  [{r['action']}] {r['orchestration_run_id']} "
                  f"client={r.get('client_id')} period={r.get('reporting_period')}"
                  + (f" — {r['reason']}" if r.get("reason") else ""))
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
