"""The access configuration, as one document an operator changes atomically.

Stage 1-3 put four separate registries under ``config/``:

    organisations.yaml   who is asking
    principals.yaml      which individual, and which organisation they belong to
    resources.yaml       what can be asked about
    entitlements.yaml    who may do what to which resource

They are separate files because they are separate concerns at runtime, but they
are one thing to *change*: adding a warehouse funder touches three of them, and
applying two of the three would leave a grant pointing at an organisation that
does not exist yet. :class:`AccessDocument` is therefore the unit of change —
read all four, apply a change set, validate the result as a whole, activate all
four together or none of them.

The document is plain data (dicts and lists, exactly the shape the Stage 1-3
loaders parse) rather than the typed registries themselves. That is deliberate:
a change set has to be able to describe an *invalid* intermediate state so the
validator can reject it with a useful message, and typed records that refuse to
be constructed cannot carry a mistake as far as the operator who needs to see it.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple

import yaml

#: Repository-relative paths, matching the defaults the Stage 1-3 loaders read
#: (``trakt_core.organisation.DEFAULT_ORGANISATION_CONFIG`` and friends).
ORGANISATIONS_FILE = "config/organisations.yaml"
PRINCIPALS_FILE = "config/principals.yaml"
RESOURCES_FILE = "config/resources.yaml"
ENTITLEMENTS_FILE = "config/entitlements.yaml"

ACCESS_FILES: Tuple[str, ...] = (
    ORGANISATIONS_FILE, PRINCIPALS_FILE, RESOURCES_FILE, ENTITLEMENTS_FILE)

#: file -> the single top-level key its list lives under.
_ROOT_KEY: Dict[str, str] = {
    ORGANISATIONS_FILE: "organisations",
    PRINCIPALS_FILE: "principals",
    RESOURCES_FILE: "resources",
    ENTITLEMENTS_FILE: "entitlements",
}

_HEADER = (
    "# Managed by the Trakt Operations Control Centre.\n"
    "#\n"
    "# Generated by activating an access change set — every entry here was\n"
    "# proposed, validated and confirmed by a named operator, and the change is\n"
    "# recorded in the OCC administrator audit trail. Editing this file by hand\n"
    "# bypasses that record; make the change through the OCC instead.\n"
)


def _entries(raw: Any, key: str) -> List[Dict[str, Any]]:
    if not isinstance(raw, Mapping):
        return []
    block = raw.get(key)
    if not block:
        return []
    if isinstance(block, Mapping):
        out = []
        for entry_id, spec in block.items():
            merged = dict(spec or {})
            merged.setdefault("organisation_id", entry_id)
            out.append(merged)
        return out
    return [dict(s or {}) for s in block if isinstance(s, Mapping)]


@dataclass
class AccessDocument:
    """The four access registries, together, as editable plain data."""

    organisations: List[Dict[str, Any]] = field(default_factory=list)
    principals: List[Dict[str, Any]] = field(default_factory=list)
    resources: List[Dict[str, Any]] = field(default_factory=list)
    entitlements: List[Dict[str, Any]] = field(default_factory=list)

    # -- construction ------------------------------------------------------- #
    @classmethod
    def empty(cls) -> "AccessDocument":
        """The state a deployment starts in: nothing configured, which is
        exactly today's ERE behaviour."""
        return cls()

    @classmethod
    def from_files(cls, files: Mapping[str, Any]) -> "AccessDocument":
        """Read from a ``ConfigPackageStore`` version's ``files`` mapping.

        Accepts either the store's ``{relpath: {"content": text}}`` shape or a
        plain ``{relpath: text}``, so a caller can build a document from loose
        YAML without constructing a package first.
        """
        def _text(rel: str) -> str:
            entry = files.get(rel)
            if entry is None:
                return ""
            if isinstance(entry, Mapping):
                return str(entry.get("content") or "")
            return str(entry)

        parsed = {}
        for rel in ACCESS_FILES:
            text = _text(rel)
            raw = yaml.safe_load(text) if text.strip() else {}
            parsed[rel] = _entries(raw, _ROOT_KEY[rel])

        return cls(
            organisations=parsed[ORGANISATIONS_FILE],
            principals=parsed[PRINCIPALS_FILE],
            resources=parsed[RESOURCES_FILE],
            entitlements=parsed[ENTITLEMENTS_FILE],
        )

    def copy(self) -> "AccessDocument":
        return AccessDocument(
            organisations=copy.deepcopy(self.organisations),
            principals=copy.deepcopy(self.principals),
            resources=copy.deepcopy(self.resources),
            entitlements=copy.deepcopy(self.entitlements),
        )

    # -- serialisation ------------------------------------------------------ #
    def to_files(self) -> Dict[str, str]:
        """``{relpath: yaml text}``, deterministically.

        Sorted and dumped with fixed options so the same document always
        produces byte-identical files — which is what lets the package store's
        content hash mean "this changed" rather than "this was rewritten".
        """
        out: Dict[str, str] = {}
        for rel, key, rows in (
            (ORGANISATIONS_FILE, "organisations", self.sorted_organisations()),
            (PRINCIPALS_FILE, "principals", self.sorted_principals()),
            (RESOURCES_FILE, "resources", self.sorted_resources()),
            (ENTITLEMENTS_FILE, "entitlements", self.sorted_entitlements()),
        ):
            body = yaml.safe_dump({key: rows}, sort_keys=True,
                                  default_flow_style=False, allow_unicode=True)
            out[rel] = _HEADER + body
        return out

    def to_dict(self) -> Dict[str, Any]:
        return {"organisations": self.sorted_organisations(),
                "principals": self.sorted_principals(),
                "resources": self.sorted_resources(),
                "entitlements": self.sorted_entitlements()}

    # -- deterministic ordering --------------------------------------------- #
    def sorted_organisations(self) -> List[Dict[str, Any]]:
        return sorted(self.organisations,
                      key=lambda o: str(o.get("organisation_id") or ""))

    def sorted_principals(self) -> List[Dict[str, Any]]:
        return sorted(self.principals,
                      key=lambda p: (str(p.get("microsoft_tenant_id") or ""),
                                     str(p.get("microsoft_object_id") or "")))

    def sorted_resources(self) -> List[Dict[str, Any]]:
        return sorted(self.resources,
                      key=lambda r: (str(r.get("tenant_id") or ""),
                                     str(r.get("kind") or ""),
                                     str(r.get("resource_id") or "")))

    def sorted_entitlements(self) -> List[Dict[str, Any]]:
        return sorted(self.entitlements,
                      key=lambda g: (str(g.get("organisation_id") or ""),
                                     str(g.get("resource") or "")))

    # -- lookup (plain-data, tolerant: the validator does the judging) ------- #
    def organisation(self, organisation_id: str) -> Optional[Dict[str, Any]]:
        wanted = str(organisation_id or "").strip().lower()
        for row in self.organisations:
            if str(row.get("organisation_id") or "").strip().lower() == wanted:
                return row
        return None

    def resource(self, reference: str) -> Optional[Dict[str, Any]]:
        wanted = _resource_key(reference)
        for row in self.resources:
            if _row_resource_key(row) == wanted:
                return row
        return None

    def principal(self, microsoft_tenant_id: str,
                  microsoft_object_id: str) -> Optional[Dict[str, Any]]:
        directory = str(microsoft_tenant_id or "").strip().lower()
        object_id = str(microsoft_object_id or "").strip().lower()
        for row in self.principals:
            if (str(row.get("microsoft_tenant_id") or "").strip().lower() == directory
                    and str(row.get("microsoft_object_id")
                            or "").strip().lower() == object_id):
                return row
        return None

    def grant(self, organisation_id: str,
              resource: str) -> Optional[Dict[str, Any]]:
        org = str(organisation_id or "").strip().lower()
        ref = _resource_key(resource)
        for row in self.entitlements:
            if (str(row.get("organisation_id") or "").strip().lower() == org
                    and _resource_key(row.get("resource")) == ref):
                return row
        return None


def _resource_key(reference: Any) -> str:
    """``"ERE/spv/spv_i"`` in comparable form.

    Only the kind and the resource id are case-folded; the tenant keeps its case
    because ``ResourceRef`` does, and a comparison that lower-cased the tenant
    would match refs the resource model treats as different.
    """
    parts = str(reference or "").strip().split("/")
    if len(parts) != 3:
        return str(reference or "").strip()
    tenant, kind, resource_id = parts
    return f"{tenant.strip()}/{kind.strip().lower()}/{resource_id.strip().lower()}"


def _row_resource_key(row: Mapping[str, Any]) -> str:
    return _resource_key(
        f"{row.get('tenant_id')}/{row.get('kind')}/{row.get('resource_id')}")
