import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import type { Artifact, KPIArtifact } from "@/domain";
import { ArtifactRenderer } from "@/components/artifacts/ArtifactRenderer";

// Fixtures are REAL /mi/query envelopes produced by the MI Agent API when its data
// source is pointed at the promoted funded central lender tape (generated by
// frontend/mi-agent-ui/scripts/generate_funded_fixtures.py). They prove the React
// UI renders the funded central tape, not synthetic demo data.
import octEnvelope from "./fixtures/funded_summary_mi_2025_10.json";
import novEnvelope from "./fixtures/funded_summary_mi_2025_11.json";

function kpiArtifactOf(envelope: { artifacts: Array<{ type: string }> }): KPIArtifact {
  const art = (envelope.artifacts as Artifact[]).find((a) => a.type === "kpi");
  if (!art) throw new Error("no kpi artifact in envelope");
  return art as KPIArtifact;
}

describe("Funded central lender tape → React dashboard", () => {
  it("mi_2025_10 renders 33 funded loans and ~£4.208MM outstanding balance", () => {
    expect(octEnvelope.ok).toBe(true);
    render(<ArtifactRenderer artifact={kpiArtifactOf(octEnvelope)} />);
    expect(screen.getByText("Loan")).toBeInTheDocument();
    expect(screen.getByText("33")).toBeInTheDocument();
    expect(screen.getByText("Current Outstanding Balance")).toBeInTheDocument();
    expect(screen.getByText("4,208,000")).toBeInTheDocument();
  });

  it("mi_2025_11 renders 73 funded loans and ~£8.903MM outstanding balance", () => {
    expect(novEnvelope.ok).toBe(true);
    render(<ArtifactRenderer artifact={kpiArtifactOf(novEnvelope)} />);
    expect(screen.getByText("73")).toBeInTheDocument();
    expect(screen.getByText("8,903,000")).toBeInTheDocument();
  });

  it("does not show the old polluted 2,196-row universe", () => {
    for (const env of [octEnvelope, novEnvelope]) {
      const balance = kpiArtifactOf(env).kpis.find((k) => /loan/i.test(k.label))?.value ?? "";
      expect(balance).not.toBe("2196");
      expect(balance).not.toBe("2,196");
    }
  });

  it("envelope is real Python-engine output, not mock", () => {
    expect(octEnvelope.metadata.mock).toBe(false);
    expect(octEnvelope.metadata.engine).toBe("mi_agent");
  });
});
