#!/usr/bin/env python3
"""package_agent.py — build a complete, client-specific Trakt Copilot agent zip.

Trakt (never the client) runs this against a per-client configuration file. The
manifests in this directory are TEMPLATES carrying ``{{TOKEN}}`` placeholders;
this script substitutes every token from the client configuration, generates
the icons, and emits ``dist/trakt-copilot-agent-<client_id>.zip``. It then
scans every packaged file and FAILS if any placeholder or unresolved template
variable survives — a zip that builds is a zip with no placeholders.

The client administrator receives the finished zip and only uploads it, grants
admin consent, and assigns users (see docs/copilot_client_deployment_runbook.md).

Client configuration (JSON):

    {
      "client_id": "ere",
      "api_base_url": "https://trakt-mi-api-ere.azurewebsites.net",
      "entra_app_id": "00000000-0000-0000-0000-000000000000",
      "app_id_uri": "api://trakt-copilot-ere",
      "sso_auth_config_id": "NDEy…",
      "scope_name": "access_as_user",
      "package_version": "1.0.0"
    }

  client_id            Stable per-client slug. The Teams app id is derived from
                       it deterministically (UUIDv5), so a rebuilt package
                       UPDATES the client's existing app instead of creating a
                       duplicate. Bump package_version on every re-issue.
  api_base_url         The client's dedicated Trakt MI API deployment.
  entra_app_id         Client id (GUID) of Trakt's multi-tenant Entra app.
                       Recorded for cross-checks; tokens are validated by the
                       API deployment, not by the package.
  app_id_uri           The Application ID URI generated by the Entra SSO auth
                       config (also added to the Entra app's identifierUris).
  sso_auth_config_id   The Microsoft Entra SSO auth-config id ("registration
                       id") from Trakt's Teams developer portal, restricted to
                       the client's Microsoft 365 organisation.
  scope_name           The scope exposed on the Entra app (e.g. access_as_user).
  package_version      Teams app package version (x.y.z).

Usage:
    python deploy/copilot-agent/package_agent.py --config clients/ere.json
    python deploy/copilot-agent/package_agent.py --config … --out /tmp/dist

No third-party dependencies: icons are minimal solid-colour PNGs generated via
zlib/struct so the package validates without binary assets in the repository.
"""

from __future__ import annotations

import argparse
import json
import re
import struct
import sys
import uuid
import zipfile
import zlib
from pathlib import Path
from urllib.parse import urlparse

HERE = Path(__file__).resolve().parent

TEMPLATE_FILES = [
    "manifest.json",
    "declarativeAgent.json",
    "ai-plugin.json",
    "trakt-copilot-openapi.yaml",
]

ACCENT_RGB = (0x1F, 0x3A, 0x5F)  # matches manifest accentColor

#: UUIDv5 namespace for deterministic per-client Teams app ids.
_APP_GUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://trakt.app/copilot-agent")

_REQUIRED_CONFIG = [
    "client_id", "api_base_url", "entra_app_id", "app_id_uri",
    "sso_auth_config_id", "scope_name",
]

#: Anything matching these in a packaged file means the build is NOT distributable.
_PLACEHOLDER_PATTERNS = [
    re.compile(r"\{\{[^}]*\}\}"),      # unsubstituted {{TOKEN}}
    re.compile(r"\$\{\{[^}]*\}\}"),    # Agents-Toolkit-style ${{VAR}}
    re.compile(r"REPLACE-WITH", re.IGNORECASE),
    re.compile(r"TRAKT-COPILOT-APP-ID"),
    re.compile(r"<[a-z0-9-]*(guid|app-id|tenant|secret|placeholder)[a-z0-9->]*>", re.IGNORECASE),
]

_GUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
_CLIENT_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")


class PackagingError(SystemExit):
    pass


def load_config(path: Path) -> dict:
    try:
        cfg = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise PackagingError(f"cannot read client config {path}: {exc}")
    missing = [k for k in _REQUIRED_CONFIG if not str(cfg.get(k) or "").strip()]
    if missing:
        raise PackagingError(f"client config missing required keys: {', '.join(missing)}")

    cfg["client_id"] = cfg["client_id"].strip()
    if not _CLIENT_ID_RE.match(cfg["client_id"]):
        raise PackagingError("client_id must be a lowercase slug ([a-z0-9_-])")
    if not _GUID_RE.match(cfg["entra_app_id"].strip()):
        raise PackagingError("entra_app_id must be a GUID")
    url = urlparse(cfg["api_base_url"].strip())
    if url.scheme != "https" or not url.hostname:
        raise PackagingError("api_base_url must be an https:// URL")
    if not cfg["app_id_uri"].strip().startswith("api://"):
        raise PackagingError("app_id_uri must start with api://")
    version = str(cfg.get("package_version") or "1.0.0").strip()
    if not _VERSION_RE.match(version):
        raise PackagingError("package_version must be x.y.z")
    cfg["package_version"] = version
    return cfg


def substitutions(cfg: dict) -> dict:
    api_base = cfg["api_base_url"].strip().rstrip("/")
    return {
        "APP_GUID": str(uuid.uuid5(_APP_GUID_NAMESPACE, cfg["client_id"])),
        "PACKAGE_VERSION": cfg["package_version"],
        "API_BASE_URL": api_base,
        "API_HOST": urlparse(api_base).hostname,
        "APP_ID_URI": cfg["app_id_uri"].strip().rstrip("/"),
        "SSO_AUTH_CONFIG_ID": cfg["sso_auth_config_id"].strip(),
        "SCOPE_NAME": cfg["scope_name"].strip(),
        "ENTRA_APP_ID": cfg["entra_app_id"].strip(),
    }


def render(template_text: str, subs: dict) -> str:
    out = template_text
    for key, value in subs.items():
        out = out.replace("{{" + key + "}}", str(value))
    return out


def assert_distributable(name: str, text: str) -> None:
    for pattern in _PLACEHOLDER_PATTERNS:
        hit = pattern.search(text)
        if hit:
            raise PackagingError(
                f"NOT DISTRIBUTABLE: {name} still contains placeholder "
                f"{hit.group(0)!r} after substitution")


def _png(width: int, height: int, rgba: tuple[int, int, int, int]) -> bytes:
    """A minimal valid RGBA PNG of one solid colour."""
    def chunk(kind: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + kind + data
                + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))

    row = b"\x00" + bytes(rgba) * width           # filter 0 + pixels
    raw = row * height
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(raw))
            + chunk(b"IEND", b""))


def build(config_path: Path, out_dir: Path) -> Path:
    cfg = load_config(config_path)
    subs = substitutions(cfg)

    rendered: dict[str, str] = {}
    for name in TEMPLATE_FILES:
        path = HERE / name
        if not path.exists():
            raise PackagingError(f"missing template file: {path}")
        text = render(path.read_text(encoding="utf-8"), subs)
        assert_distributable(name, text)
        if name.endswith(".json"):
            json.loads(text)  # fail fast on structurally broken output
        rendered[name] = text

    # Cross-consistency: the OpenAPI scope must reference the configured
    # Application ID URI, and the plugin must carry the SSO auth config id.
    if subs["APP_ID_URI"] not in rendered["trakt-copilot-openapi.yaml"]:
        raise PackagingError("OpenAPI spec does not reference the app_id_uri")
    if subs["SSO_AUTH_CONFIG_ID"] not in rendered["ai-plugin.json"]:
        raise PackagingError("ai-plugin.json does not carry the sso_auth_config_id")

    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"trakt-copilot-agent-{cfg['client_id']}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, text in rendered.items():
            zf.writestr(name, text)
        zf.writestr("color.png", _png(192, 192, (*ACCENT_RGB, 255)))
        zf.writestr("outline.png", _png(32, 32, (255, 255, 255, 255)))

    # Belt and braces: re-scan the bytes actually written into the zip.
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.endswith(".png"):
                continue
            assert_distributable(name, zf.read(name).decode("utf-8"))
    return zip_path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", required=True,
                    help="path to the per-client configuration JSON")
    ap.add_argument("--out", default=str(HERE / "dist"),
                    help="output directory (default: deploy/copilot-agent/dist)")
    args = ap.parse_args(argv)
    zip_path = build(Path(args.config), Path(args.out))
    print(f"wrote {zip_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
