"""simulation.dialects.lender_excel — a UK lender's XLSX export.

What this dialect deliberately exercises:

* the lender's OWN header vocabulary, resolved through the approved onboarding
  contract rather than the global alias library;
* a worksheet name that varies by reporting period;
* a column order that is not the canonical order;
* a second worksheet carrying export metadata;
* mixed date presentation (``31 Jan 2025`` alongside ISO);
* percentages written as display-formatted values (``43.10%``);
* thousands-separated money (``1,234,567.89``);
* blank optional columns, present but unpopulated;
* additional columns that carry no canonical meaning at all.

What it deliberately does NOT do: merged cells, header rows below row 1, or
multi-row headers. ``semantic_alignment.read_input_table`` calls
``pandas.read_excel(path)`` with defaults, so it reads the FIRST worksheet with a
single header row — decorating beyond that would test a capability the ingestion
path does not claim.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Sequence

from ..assets import get_profile
from ..models import DIALECT_LENDER_EXCEL, CaseManifest, SchemaEvolution
from . import register
from . import _format as F
from ._plan import build_plan
from .vocabulary import OPTIONAL_OMISSIONS

#: Percentage-valued canonical fields, written as display strings here.
_PERCENT_FIELDS = ("current_loan_to_value", "original_loan_to_value",
                   "current_interest_rate")

#: Date fields written in the long presentation rather than ISO.
_LONG_DATE_FIELDS = ("origination_date", "maturity_date")

#: Worksheet name per reporting period — a real lender's export varies it.
_SHEET_NAMES = ("Loan Book", "LoanBook", "Loan Book Extract", "Portfolio",
                "Loan Book (Final)", "Loan Book Data")


def _value(field: str, raw: Any, formats: Dict[str, str], enum_style: str) -> Any:
    if raw in (None, ""):
        return ""
    if field == "account_status":
        table = (F.STATUS_SYNONYMS_ALTERNATE if enum_style == "alternate"
                 else F.STATUS_SYNONYMS_LENDER)
        return table.get(str(raw), str(raw))
    if field in _PERCENT_FIELDS:
        return F.percent_string(raw, 2)
    fmt = formats.get(field, "")
    if fmt == "date":
        return F.long_date(raw) if field in _LONG_DATE_FIELDS else F.iso_date(raw)
    if fmt == "decimal":
        return F.thousands_grouped(raw, 2)
    if fmt == "integer":
        return F.integer(raw)
    if fmt == "Y/N":
        return F.boolean(raw, "yesno")
    return F.text(raw)


def render(rows: List[Dict[str, Any]], case: CaseManifest, *, period_index: int,
           reporting_date: str, out_dir: Path,
           evolution: Sequence[SchemaEvolution] = ()) -> Path:
    from openpyxl import Workbook

    from .._registry import field_formats

    profile = get_profile(case.asset_class)
    formats = field_formats(case.asset_class)
    plan = build_plan(case, flavour="lender", period_index=period_index,
                      fields=profile.canonical_fields, evolution=evolution,
                      with_extras=True)
    # A column the lender exports but never populates.
    blanked = set(OPTIONAL_OMISSIONS.get(case.asset_class, ())[:1])

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / (f"{case.portfolio_id}_{reporting_date.replace('-', '')}"
                      f"_lender.xlsx")

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = _SHEET_NAMES[period_index % len(_SHEET_NAMES)]
    sheet.append(plan.headers)
    for row in rows:
        line = [("" if canon in blanked
                 else _value(canon, row.get(canon), formats, plan.enum_style))
                for _header, canon in plan.columns]
        line += [""] * len(plan.extras)
        sheet.append(line)

    # A second worksheet the ingestion path does not read. It exists because
    # real lender exports carry one, and its presence must not change anything.
    meta = workbook.create_sheet("Export Metadata")
    meta.append(["Key", "Value"])
    for key, value in (
        ("Portfolio", case.portfolio_id),
        ("Reporting Date", reporting_date),
        ("Currency", case.currency),
        ("Rows", str(len(rows))),
        ("Blanked Columns", ", ".join(sorted(blanked))),
        ("Generated By", f"trakt simulation v{case.simulation_version}"),
    ):
        meta.append([key, value])

    workbook.save(path)
    return path


register(DIALECT_LENDER_EXCEL, render)

__all__ = ["render"]
