/**
 * Every user-facing string used by the app chrome and labels.
 * Plain, calm, non-technical English only — a test enforces this.
 */
export const copy = {
  appName: "Trakt Operations",

  nav: {
    home: "Home",
    review: "Review",
    workflows: "Workflows",
    rules: "Rules",
    history: "History",
    admin: "Platform configuration",
    startNew: "Start something new",
  },

  signIn: {
    title: "Trakt Operations",
    prompt: "Paste your access key",
    helper: "Your access key was shared with you by your Trakt administrator.",
    placeholder: "Access key",
    button: "Continue",
  },

  errors: {
    network: "Trakt could not be reached. Check your connection and try again.",
    signedOut: "Your access key is no longer valid. Please sign in again.",
    generic: "Something went wrong. Please try again.",
    retry: "Try again",
  },

  common: {
    loading: "Loading…",
    decisionOne: "decision",
    decisionMany: "decisions",
    version: "Version",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    close: "Close",
    optionalReason: "Why? (optional)",
    showDetails: "Show details",
  },

  home: {
    title: "Trakt Operations",
    subtitle: "What Trakt is preparing for you, and what needs you.",
    tiles: {
      new_deliveries: "New deliveries",
      needs_attention: "Needs your attention",
      blocked: "Blocked",
      ready_to_publish: "Ready to publish",
      recently_published: "Recently published",
    },
    needsAttention: "Needs your attention",
    recentlyPublished: "Recently published",
    emptyAttention: "Nothing needs your attention.",
    emptyPublished: "Nothing has been published recently.",
  },

  newWorkflow: {
    title: "Start something new",
    outcomeHeading: "What would you like Trakt to prepare?",
    outcomeMi: "MI Reporting",
    outcomeMiHelp: "The regular management information pack.",
    outcomeAnnex: "MI Reporting + ESMA Annex 2 delivery",
    outcomeAnnexHelp: "The regular pack plus the regulatory annex.",
    detailsHeading: "Who is this for?",
    clientLabel: "Client",
    clientPlaceholder: "Choose a client",
    newClientOption: "New client…",
    newClientLabel: "New client name",
    portfolioLabel: "Portfolio",
    periodLabel: "Reporting period",
    createButton: "Continue",
    filesHeading: "Which files should Trakt use?",
    folderLabel: "Where are the files?",
    folderHelper: "Paste the location your files were saved to — a single file or a whole folder.",
    addFilesButton: "Add the files",
  },

  batch: {
    inputPack: "Input pack",
    roleReceived: "✓ Received and recognised",
    roleWaiting: "Waiting",
    roleOptional: "Optional — not provided",
    filesHeading: "Files received",
    noFiles: "No files have arrived yet.",
    configuration: "Configuration",
    configReady: "✓ Ready",
    configNeeded: "Configuration needed",
    blockingDecisions: "Blocking decisions",
    none: "None",
    addFilesHeading: "Add files",
    addFilesButton: "Add files",
    startButton: "Start onboarding",
    autoStartNote: "Trakt will start this on its own as soon as everything has arrived.",
    viewWorkflow: "See the workflow",
    notFound: "That input pack could not be found.",
  },

  workflows: {
    title: "Workflows",
    subtitle: "Everything Trakt is working on.",
    filterAll: "All",
    filterNeedsReview: "Needs review",
    filterBlocked: "Blocked",
    filterReady: "Ready to publish",
    filterPublished: "Published",
    empty: "No workflows here yet.",
  },

  workflow: {
    reviewDecisions: "Review decisions",
    runAgain: "Run again",
    approvePublish: "Approve and publish",
    hold: "Hold",
    publishConfirm: "Publish this report as the latest official version?",
    publishButton: "Publish",
    holdPrompt: "Why are you holding this report?",
    holdButton: "Hold this report",
    warningsHeading: "Worth knowing",
    blockersHeading: "What's in the way",
    notFound: "That workflow could not be found.",
  },

  reviews: {
    title: "Review",
    subtitle: "Questions Trakt needs you to answer.",
    empty: "Nothing to review right now.",
    blockingChip: "Needed to continue",
    optionalChip: "Optional",
    recommendedHeading: "Trakt suggests",
    scopeHeading: "Where should this answer apply?",
    somethingElse: "It's something else",
    somethingElsePlaceholder: "Tell Trakt what this means",
    confirm: "Confirm",
    reject: "This is wrong",
    rejectReason: "Tell Trakt why, so it can do better",
    savedRerun: "Saved. Trakt is re-running the affected step.",
    saved: "Saved.",
    backToList: "Back to review",
    notFound: "That question could not be found.",
  },

  scopes: {
    file: "This delivery only",
    portfolio: "This portfolio",
    client: "This client",
    global: "All of Trakt",
  },

  rules: {
    title: "Rules",
    subtitle: "Everything Trakt has learned, approved by your team.",
    searchPlaceholder: "Search rules",
    kindAll: "All kinds",
    scopeAll: "All scopes",
    sourceTerm: "What the file says",
    approvedMeaning: "What it means",
    approvedBy: "Approved by",
    historyHeading: "Earlier versions",
    empty: "No rules match.",
  },

  history: {
    title: "History",
    subtitle: "Every report Trakt has prepared, by client.",
    builtWithPrefix: "built with",
    builtWithSuffix: "approved rules",
    previousVersion: "Previous version available",
    empty: "No reports yet.",
  },

  admin: {
    title: "Platform configuration",
    subtitle: "The settings administrators control, and how they are versioned.",
    tabs: {
      overview: "Overview",
      system: "System",
      assets: "Assets",
      regimes: "Regimes",
      history: "History",
    },
    accessDeniedTitle: "Access denied",
    accessDenied: "You do not have permission to administer platform configuration.",
    accessDeniedHelp: "If you think this is wrong, ask your Trakt administrator.",
    unavailable:
      "Configuration administration is temporarily unavailable. No configuration has been changed.",

    activeVersion: "Active version",
    draftVersion: "Draft version",
    priorVersions: "Earlier versions",
    status: "Status",
    activatedAt: "Activated",
    activatedBy: "Activated by",
    createdBy: "Created by",
    createdAt: "Created",
    basedOn: "Based on version",
    fingerprint: "Fingerprint",
    partCount: "Parts",
    notes: "Notes",
    noNotes: "No notes were added.",

    sections: {
      summary: "Summary",
      dependencies: "Dependencies",
      files: "Parts",
      history: "History",
      impact: "Impact",
      compare: "Compare",
    },

    actions: {
      reviewActive: "Review active version",
      createDraft: "Create a draft",
      compare: "Compare",
      validate: "Check this draft",
      activate: "Activate",
      rollback: "Roll back",
      inspect: "Inspect",
      viewPart: "Open",
      closePart: "Close",
      showTechnical: "Show technical details",
      hideTechnical: "Hide technical details",
    },

    draft: {
      heading: "Draft awaiting action",
      none: "There is no draft version for this package.",
      chip: "Draft",
      changedParts: "What changed",
      noChanges: "This draft is an exact copy of the version it was based on.",
      createPrompt: "Create a draft copy of the active version?",
      createHelp:
        "A draft changes nothing on its own. It must pass its checks and be activated before Trakt uses it.",
      createButton: "Create draft",
      created: "Draft created. Check it before activating.",
      readOnlyNote:
        "Drafts are reviewed here and prepared through the supported change process. This screen never edits an active version.",
    },

    validation: {
      heading: "Checks",
      notChecked: "Not checked yet",
      pass: "Checks passed",
      fail: "Validation failed",
      running: "Checking…",
      done: "Checks finished.",
      problemsHeading: "What is in the way",
      warningsHeading: "Worth knowing",
      dependenciesHeading: "What this affects",
    },

    activate: {
      heading: "Activate this version?",
      package: "Package",
      version: "Version",
      replaces: "Replaces version",
      pinnedNote: "Workflows that have already started stay on the version they began with.",
      futureNote: "Only workflows started after this point will use the new version.",
      historyNote: "Reports that have already been published are unchanged.",
      button: "Activate",
      done: "Activated. Future workflows will use this version.",
      blockedHeading: "This cannot be activated",
      invalidHelp: "This version has not passed its checks yet.",
    },

    rollback: {
      heading: "Roll back to an earlier version?",
      help: "The version being replaced is kept, not deleted. You can move forward again later.",
      button: "Roll back",
      done: "Rolled back. Future workflows will use the earlier version.",
      choose: "Which version should Trakt go back to?",
    },

    compare: {
      heading: "Compare versions",
      from: "From",
      to: "To",
      added: "Added",
      changed: "Changed",
      removed: "Removed",
      unchanged: "Unchanged",
      identical: "These two versions are identical.",
      truncated: "Only the first part of this change is shown.",
      pick: "Choose two versions to compare.",
    },

    files: {
      heading: "What is in this package",
      empty: "This version has no parts.",
      size: "Size",
      readOnly: "Read only. Active versions can never be edited here.",
    },

    compatibility: {
      heading: "Which assets can report under which regimes",
      supported: "Supported",
      notSupported: "Not supported",
      asset: "Asset",
      blockerHeading: "Compatibility",
      none: "No compatibility problems were found.",
    },

    impact: {
      heading: "Potential impact",
      clients: "Clients using this package",
      portfolios: "Portfolios using this package",
      running: "Running workflows pinned to this version",
      pinned: "Workflows pinned to this version",
      future: "Future workflows affected after activation",
      yes: "Yes",
      workflowsHeading: "Pinned workflows",
      none: "Nothing is using this version yet.",
    },

    audit: {
      title: "Configuration history",
      subtitle: "Every configuration change, who made it, and what it means.",
      empty: "No configuration changes have been made yet.",
      chainIntact: "This history is complete and unaltered.",
      chainBroken: "This history could not be confirmed as complete. Tell your administrator.",
    },

    overview: {
      heading: "Platform configuration",
      systemHeading: "System package",
      assetHeading: "Asset packages",
      regimeHeading: "Regime packages",
      attentionHeading: "Needs an administrator",
      noAttention: "Nothing needs an administrator right now.",
      draftsAwaiting: "Drafts awaiting action",
      validationFailures: "Checks that failed",
      requiresReview: "Not checked yet",
      compatibilityIssues: "Worth knowing",
      recentActivations: "Recent activations",
      recentRollbacks: "Recent roll backs",
      noRecent: "No recent changes.",
    },

    system: {
      title: "System configuration",
      subtitle: "The platform-wide settings every client shares.",
    },

    assets: {
      title: "Asset configuration",
      subtitle: "The product settings that describe how each asset type behaves.",
      supportedRegimes: "Supported regimes",
      sourceSemantics: "How source data is read",
      mappingDefaults: "Default settings",
      taxonomies: "Groupings",
      profiles: "Product profiles",
      settings: "Settings",
      empty: "No asset packages are configured.",
      clientNote:
        "Client and portfolio settings are not administered here. They stay part of onboarding.",
    },

    regimes: {
      title: "Regime configuration",
      subtitle: "The regulatory packages Trakt can report under.",
      regulator: "Regulator",
      annex: "Annex",
      packageVersion: "Package version",
      schema: "Schema",
      draftSchema: "This is a draft schema published by the regulator.",
      fieldUniverse: "Fields covered",
      codeOrder: "Field order",
      validationPolicy: "Checking policy",
      noDataPolicy: "Missing-value policy",
      unknownValues: "Unexpected values",
      deferred: "Deferred fields",
      allowedCodes: "Codes allowed when a value is missing",
      fieldsAllowing: "Fields that may be left empty",
      compatibleAssets: "Compatible assets",
      empty: "No regime packages are configured.",
    },
  },

  statusLabels: {
    received: "Received",
    running: "In progress",
    needs_review: "Needs review",
    blocked: "Blocked",
    awaiting_publication: "Ready to publish",
    published: "Published",
    held: "On hold",
    cancelled: "Cancelled",
    failed: "Did not finish",
    waiting: "Waiting",
    ready: "Ready",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Done",
    open: "Open",
    resolved: "Resolved",
    prepared: "Prepared",
    receiving: "Receiving files",
    incomplete: "Waiting for files",
    classifying: "Looking at the files",
    review_required: "Needs review",
    configuration_required: "Configuration needed",
    // Configuration package lifecycle (the administrator area).
    draft: "Draft",
    active: "Active",
    superseded: "Replaced",
    valid: "Valid",
    not_checked: "Not checked",
    passed: "Valid",
    failed_checks: "Not valid",
  } as Record<string, string>,
};

export function decisionsLabel(n: number): string {
  return `${n} ${n === 1 ? copy.common.decisionOne : copy.common.decisionMany}`;
}
