#!/usr/bin/env python3
"""Build the Annex 2 mapping-correction impact report (artefact 49).

Report-only. Compares two onboarding-workflow run directories — a BASE run
(pre-correction regime config) and an AFTER run (Part B corrected config) — for
the 17 proposed corrected ESMA codes, and writes:

    49_annex2_mapping_correction_impact.csv
    49_annex2_mapping_correction_impact.json
    49_annex2_mapping_correction_impact_summary.md

Both runs must use the SAME input/universe/registry and differ only in
--regime-config (base vs corrected delivery rules). XML is NOT generated by the
onboarding workflow, so value impact is inferred from the projected / 28a
selected values; XML element placement is independent of these fields (it is
driven by code_order / esma_model_structure / ESMA code in gate 5).

Usage:
    python due_diligence/build_annex2_impact_report.py \
        --before-dir /tmp/impact_before --after-dir /tmp/impact_after \
        --out-dir due_diligence
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import yaml

CODES = ["RREL10", "RREL13", "RREL14", "RREL17", "RREL26", "RREL64", "RREL66",
         "RREL70", "RREL72", "RREL75", "RREL76", "RREL78", "RREL79", "RREL80",
         "RREL81", "RREC21", "RREC23"]

COLUMNS = [
    "esma_code", "workbook_field_name", "current_regime_source_before",
    "proposed_regime_source_after", "registry_canonical_field",
    "coverage_status_before", "coverage_status_after", "selected_value_before",
    "selected_value_after", "selected_source_file_before",
    "selected_source_file_after", "selected_source_column_before",
    "selected_source_column_after", "default_value_before", "default_value_after",
    "nd_allowed_before", "nd_allowed_after", "appears_in_28c_before",
    "appears_in_28c_after", "decision_type_before", "decision_type_after",
    "xml_value_before", "xml_value_after", "xml_changed", "xml_placement_changed",
    "risk_level", "recommended_action", "message",
]

_REPO = Path(__file__).resolve().parent.parent


def _load_run(d: Path):
    a = {r["esma_code"]: r for r in
         json.loads((d / "28a_target_coverage_matrix.json").read_text())["rows"]}
    c = {r["esma_code"]: r for r in
         json.loads((d / "28c_human_decision_queue.json").read_text())["rows"]}
    return a, c


def _eff(row):
    """Effective projected value = selected value if present else default."""
    return (str(row.get("selected_value") or "").strip()
            or str(row.get("default_value") or "").strip())


def _nd(row):
    """nd_allowed may be a list or an already-joined string; normalise to str."""
    v = row.get("nd_allowed")
    if isinstance(v, (list, tuple)):
        return "; ".join(str(x) for x in v)
    return str(v or "")


def build(before_dir: Path, after_dir: Path):
    ab, cb = _load_run(before_dir)
    aa, ca = _load_run(after_dir)
    wb = yaml.safe_load(
        (_REPO / "config/regime/annex2_field_universe.yaml").read_text())["fields"]
    reg = yaml.safe_load(
        (_REPO / "config/system/fields_registry.yaml").read_text())["fields"]
    code2canon = {}
    for fname, meta in reg.items():
        c = ((meta.get("regime_mapping") or {}).get("ESMA_Annex2") or {}).get("code")
        if c:
            code2canon[c] = fname

    rows = []
    for code in CODES:
        b, a = ab.get(code, {}), aa.get(code, {})
        col_b = str(b.get("selected_source_column") or "")
        col_a = str(a.get("selected_source_column") or "")
        sm_b = b.get("coverage_status") == "source_mapped"
        sm_a = a.get("coverage_status") == "source_mapped"
        eff_b, eff_a = _eff(b), _eff(a)
        binding_changed = col_b != col_a
        value_changed = eff_b != eff_a
        # XML not generated by onboarding; projected value is the proxy. The
        # emitted value would differ when the (now-correct) source is populated.
        xml_changed = bool(binding_changed or value_changed)

        # Outcome of the AFTER state.
        if sm_a and not sm_b:
            outcome = "correct source value (now mapped to the right column)"
            risk = "high"
            action = "approve; validate the emitted value against real client data"
        elif sm_a and sm_b and binding_changed:
            outcome = "correct source value (rebound from a wrong column)"
            risk = "high"
            action = "approve (fixes a wrong source binding); validate against real data"
        elif sm_b and not sm_a:
            outcome = "valid ND/default fallback (correct source column absent)"
            risk = "high"
            action = ("approve (removes a wrong-column value); wire the correct "
                      "source column or confirm ND fallback")
        elif value_changed:
            outcome = "default/config value changed"
            risk = "medium"
            action = "approve; confirm the default/config value is intended"
        else:
            outcome = "valid ND/default fallback (unchanged output)"
            risk = "low"
            action = ("safe to apply (output unchanged); separately wire the correct "
                      "source column — currently a valid ND fallback")

        before_wrong = sm_b and binding_changed
        msg = (f"source {b.get('projected_source_field','')!r} -> "
               f"{a.get('projected_source_field','')!r}; {outcome}.")
        if before_wrong:
            msg = ("BEFORE bound to the wrong column "
                   f"{col_b!r}; " + msg)
        if str(b.get("nd_allowed")) != str(a.get("nd_allowed")):
            msg += (f" nd_allowed {b.get('nd_allowed')} -> {a.get('nd_allowed')}.")

        rows.append({
            "esma_code": code,
            "workbook_field_name": wb.get(code, {}).get("field_name", ""),
            "current_regime_source_before": b.get("projected_source_field", ""),
            "proposed_regime_source_after": a.get("projected_source_field", ""),
            "registry_canonical_field": code2canon.get(code, ""),
            "coverage_status_before": b.get("coverage_status", ""),
            "coverage_status_after": a.get("coverage_status", ""),
            "selected_value_before": b.get("selected_value", ""),
            "selected_value_after": a.get("selected_value", ""),
            "selected_source_file_before": b.get("selected_source_file", ""),
            "selected_source_file_after": a.get("selected_source_file", ""),
            "selected_source_column_before": col_b,
            "selected_source_column_after": col_a,
            "default_value_before": b.get("default_value", ""),
            "default_value_after": a.get("default_value", ""),
            "nd_allowed_before": _nd(b),
            "nd_allowed_after": _nd(a),
            "appears_in_28c_before": code in cb,
            "appears_in_28c_after": code in ca,
            "decision_type_before": cb.get(code, {}).get("decision_type", ""),
            "decision_type_after": ca.get(code, {}).get("decision_type", ""),
            "xml_value_before": eff_b,
            "xml_value_after": eff_a,
            "xml_changed": xml_changed,
            "xml_placement_changed": False,
            "risk_level": risk,
            "recommended_action": action,
            "message": msg,
        })
    return rows


def artefact_deltas(before_dir: Path, after_dir: Path):
    """Before/after of the related reconciliation artefacts (43/44/45/47/48)
    plus the 40 summary headline counts, so 49 is self-contained."""
    def js(d, n):
        p = d / f"{n}.json"
        return json.loads(p.read_text()) if p.exists() else {}

    def sm(d, n):
        return js(d, n).get("summary", {})

    b40, a40 = js(before_dir, "40_operator_workflow_summary"), js(after_dir, "40_operator_workflow_summary")
    out = {"40_summary": {}}
    for k in ("annex2_semantic_mismatch_count", "annex2_enum_constrained_count",
              "annex2_enum_unconstrained_count", "annex2_mapping_proposals_total"):
        out["40_summary"][k] = {"before": b40.get(k), "after": a40.get(k)}
    for n, keys in (
        ("43_annex2_field_universe_reconciliation",
         ("authoritative_field_count", "registry_gap_count", "missing_from_regime_rules_count")),
        ("44_annex2_nd_eligibility_reconciliation",
         ("regime_broader", "divergent", "regime_stricter", "aligned")),
        ("45_annex2_config_alignment_review", ("requires_manual_review_count",)),
        ("47_annex2_semantic_mapping_reconciliation", ("semantic_mismatch", "aligned")),
        ("48_annex2_mapping_correction_proposals", ("proposal_rows_total",)),
    ):
        b, a = sm(before_dir, n), sm(after_dir, n)
        out[n] = {k: {"before": b.get(k), "after": a.get(k)} for k in keys}
    return out


def summarise(rows):
    risk = {}
    for r in rows:
        risk[r["risk_level"]] = risk.get(r["risk_level"], 0) + 1
    return {
        "codes_total": len(rows),
        "risk_low": risk.get("low", 0),
        "risk_medium": risk.get("medium", 0),
        "risk_high": risk.get("high", 0),
        "risk_manual_review": risk.get("manual_review", 0),
        "xml_value_changes": sum(1 for r in rows if r["xml_changed"]),
        "xml_placement_changes": sum(1 for r in rows if r["xml_placement_changed"]),
        "before_wrong_column_bindings": sum(
            1 for r in rows if r["coverage_status_before"] == "source_mapped"
            and r["selected_source_column_before"] != r["selected_source_column_after"]),
        "after_nd_default_fallback": sum(
            1 for r in rows if str(r["coverage_status_after"]).startswith("defaulted")),
        "appears_in_28c_after": sum(1 for r in rows if r["appears_in_28c_after"]),
        "risk_counts": risk,
        "xml_generation_available": False,
        "xml_note": ("XML value comparison not available in current workflow; "
                     "impact inferred from projected source/value changes."),
        "workbook_semantic_affects_xml_placement": False,
        "workbook_semantic_affects_value_selection": True,
        "projected_source_field_affects_value_selection": True,
    }


def write(out_dir: Path, rows, summary, deltas, before_dir, after_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    with (out_dir / "49_annex2_mapping_correction_impact.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    (out_dir / "49_annex2_mapping_correction_impact.json").write_text(
        json.dumps({"base_run": str(before_dir), "after_run": str(after_dir),
                    "summary": summary, "artefact_deltas": deltas, "rows": rows},
                   indent=2, default=str))

    def fmt(r):
        return (f"- `{r['esma_code']}` {r['workbook_field_name']} "
                f"[{r['risk_level']}]: {r['message']} "
                f"(xml_changed={r['xml_changed']})")

    md = [
        "# Annex 2 mapping-correction impact report (49)", "",
        "Report-only before/after comparison for the 17 proposed corrected ESMA "
        "codes. Base = `claude/annex2-target-first-workflow-frnu7h`; "
        "After = `claude/annex2-mapping-corrections-proposed`. No rules changed "
        "by this report.", "",
        "## XML placement independence", "",
        "- **workbook_semantic affects XML placement: no** — placement is driven "
        "by `code_order` / `esma_model_structure` / ESMA code in gate 5 "
        "(`xml_builder_annex2`), not by `workbook_semantic`.",
        "- **workbook_semantic affects value selection: yes (secondary only)** — "
        "used as a fuzzy-match synonym and display label; `projected_source_field` "
        "is the primary selector.",
        "- **projected_source_field affects value selection: yes (primary)** — it "
        "is the `match_field` the coverage engine binds the source column to.", "",
        "## XML availability", "",
        f"- {summary['xml_note']}", "",
        "## Summary", "",
        f"- Codes compared: **{summary['codes_total']}**",
        f"- Risk — low: **{summary['risk_low']}**, medium: "
        f"**{summary['risk_medium']}**, high: **{summary['risk_high']}**, "
        f"manual_review: **{summary['risk_manual_review']}**",
        f"- Projected-value changes (with populated source): "
        f"**{summary['xml_value_changes']}**",
        f"- XML placement changes: **{summary['xml_placement_changes']}**",
        f"- BEFORE bound to a WRONG source column (active data error fixed): "
        f"**{summary['before_wrong_column_bindings']}**",
        f"- AFTER resolves to a valid ND/default fallback: "
        f"**{summary['after_nd_default_fallback']}**",
        f"- Appears in 28c after: **{summary['appears_in_28c_after']}**", "",
        "## Related artefact deltas (before -> after)", "",
    ]
    for art, kv in deltas.items():
        md.append(f"- **{art}**: " + ", ".join(
            f"{k} {v['before']}->{v['after']}" for k, v in kv.items()))
    md += ["", "## Per-code impact", ""]
    for level in ("high", "medium", "low", "manual_review"):
        sel = [r for r in rows if r["risk_level"] == level]
        if sel:
            md.append(f"### {level} ({len(sel)})")
            md += [fmt(r) for r in sel]
            md.append("")
    (out_dir / "49_annex2_mapping_correction_impact_summary.md").write_text(
        "\n".join(md) + "\n")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--before-dir", required=True)
    p.add_argument("--after-dir", required=True)
    p.add_argument("--out-dir", default=str(Path(__file__).resolve().parent))
    args = p.parse_args()
    rows = build(Path(args.before_dir), Path(args.after_dir))
    summary = summarise(rows)
    deltas = artefact_deltas(Path(args.before_dir), Path(args.after_dir))
    write(Path(args.out_dir), rows, summary, deltas, args.before_dir, args.after_dir)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
