/**
 * Generate the voice-over script, the caption file and the scene timing sheet
 * from `src/timeline.ts` — the same table the film renders from.
 *
 *   node scripts/generate-script.mjs
 *
 * Writing these by hand would let them drift from the film. Generating them means
 * a timing change in the timeline is a timing change in the subtitles, the script
 * and the music markers, in one step.
 *
 * Outputs, into `out/`:
 *   voiceover-script.md          full script with per-scene timings
 *   captions.srt                 SubRip subtitles (the on-screen captions)
 *   captions.vtt                 WebVTT subtitles, for web players
 *   scene-timings.csv            scene-level timing sheet
 *   music-markers.md             optional background-music timing markers
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT = join(ROOT, "out");
mkdirSync(OUT, { recursive: true });

// The timeline is TypeScript; strip the types with esbuild (already a Remotion
// dependency) rather than adding a loader.
const { build } = await import("esbuild");
const bundled = await build({
  entryPoints: [join(ROOT, "src", "timeline.ts")],
  bundle: true,
  format: "esm",
  write: false,
  platform: "node",
  target: "node18",
});
const moduleUrl =
  "data:text/javascript;base64," +
  Buffer.from(bundled.outputFiles[0].text).toString("base64");
const { FPS, SCENES, sceneStarts, totalFrames } = await import(moduleUrl);

/**
 * Absolute scene start times, in seconds. Scene transitions are hard cuts, so a
 * scene starts exactly where the previous one ends — there is no overlap to net off.
 */
const sceneStartSeconds = () => sceneStarts().map((frame) => frame / FPS);

const timecode = (seconds, separator = ",") => {
  const totalMs = Math.round(seconds * 1000);
  const ms = totalMs % 1000;
  const totalSec = Math.floor(totalMs / 1000);
  const h = String(Math.floor(totalSec / 3600)).padStart(2, "0");
  const m = String(Math.floor((totalSec % 3600) / 60)).padStart(2, "0");
  const s2 = String(totalSec % 60).padStart(2, "0");
  return `${h}:${m}:${s2}${separator}${String(ms).padStart(3, "0")}`;
};

const clock = (seconds) => {
  const m = Math.floor(seconds / 60);
  const s2 = Math.round(seconds % 60);
  return `${m}:${String(s2).padStart(2, "0")}`;
};

const starts = sceneStartSeconds();
const total = totalFrames() / FPS;

// --------------------------------------------------------------------------- //
// Voice-over script
// --------------------------------------------------------------------------- //
const wordCount = (text) => text.trim().split(/\s+/).length;

const scriptLines = [
  "# Trakt product demonstration — voice-over script",
  "",
  "SYNTHETIC DEMONSTRATION DATA — NOT A REAL CUSTOMER.",
  "",
  "Generated from `demo-video/src/timeline.ts`. Do not edit this file by hand:",
  "change the timeline and re-run `node scripts/generate-script.mjs`.",
  "",
  `Total run time **${clock(total)}** (${total.toFixed(1)}s at ${FPS} fps).`,
  "",
  "The film is caption-led and fully intelligible with the audio muted. This",
  "script is provided so a narration track can be added without re-timing the",
  "film: each paragraph is written to sit inside its scene at a normal reading",
  "pace of roughly 150 words per minute, and the pace column below shows the",
  "headroom in each scene.",
  "",
  "| Scene | In | Out | Length | Words | Words/min |",
  "|---|---|---|---|---|---|",
];

SCENES.forEach((scene, i) => {
  const words = wordCount(scene.narration);
  const wpm = Math.round((words / (scene.frames / FPS)) * 60);
  scriptLines.push(
    `| ${scene.number}. ${scene.title} | ${clock(starts[i])} | ` +
      `${clock(starts[i] + (scene.frames / FPS))} | ${(scene.frames / FPS).toFixed(1)}s | ${words} | ${wpm} |`,
  );
});

scriptLines.push("", "---", "");

SCENES.forEach((scene, i) => {
  scriptLines.push(
    `## Scene ${scene.number} — ${scene.title}`,
    "",
    `**${clock(starts[i])} → ${clock(starts[i] + (scene.frames / FPS))}** ` +
      `(${(scene.frames / FPS).toFixed(1)}s, ${wordCount(scene.narration)} words)`,
    "",
    scene.narration,
    "",
    "On-screen captions:",
    "",
  );
  scene.captions.forEach((caption) => {
    scriptLines.push(
      `- \`${clock(starts[i] + (caption.at / FPS))}\` ${caption.text}` +
        "",
    );
  });
  scriptLines.push("");
});

writeFileSync(join(OUT, "voiceover-script.md"), scriptLines.join("\n"), "utf8");

// --------------------------------------------------------------------------- //
// Subtitles — the on-screen captions, at their exact times
// --------------------------------------------------------------------------- //
const cues = [];
SCENES.forEach((scene, i) => {
  scene.captions.forEach((caption) => {
    const start = starts[i] + caption.at / FPS;
    cues.push({
      start,
      end: start + caption.hold / FPS,
      text: caption.text,
    });
  });
});
cues.sort((a, b) => a.start - b.start);

const srt = cues
  .map(
    (cue, i) =>
      `${i + 1}\n${timecode(cue.start)} --> ${timecode(cue.end)}\n${cue.text}\n`,
  )
  .join("\n");
writeFileSync(join(OUT, "captions.srt"), srt, "utf8");

const vtt =
  "WEBVTT\n\nNOTE Trakt product demonstration — synthetic data\n\n" +
  cues
    .map(
      (cue, i) =>
        `${i + 1}\n${timecode(cue.start, ".")} --> ${timecode(cue.end, ".")}\n${cue.text}\n`,
    )
    .join("\n");
writeFileSync(join(OUT, "captions.vtt"), vtt, "utf8");

// --------------------------------------------------------------------------- //
// Scene timing sheet
// --------------------------------------------------------------------------- //
const csv = [
  "scene,title,in_seconds,out_seconds,length_seconds,in_frame,out_frame,narration_words",
  ...SCENES.map((scene, i) =>
    [
      scene.number,
      `"${scene.title}"`,
      starts[i].toFixed(2),
      (starts[i] + (scene.frames / FPS)).toFixed(2),
      (scene.frames / FPS).toFixed(2),
      Math.round(starts[i] * FPS),
      Math.round((starts[i] + (scene.frames / FPS)) * FPS),
      wordCount(scene.narration),
    ].join(","),
  ),
].join("\n");
writeFileSync(join(OUT, "scene-timings.csv"), `${csv}\n`, "utf8");

// --------------------------------------------------------------------------- //
// Music markers
// --------------------------------------------------------------------------- //
const music = [
  "# Background-music timing markers",
  "",
  "SYNTHETIC DEMONSTRATION DATA — NOT A REAL CUSTOMER.",
  "",
  "The film ships **silent**. No music is embedded: commercial tracks are",
  "copyrighted and the repository carries no licensed audio asset. If a track is",
  "licensed later, these are the markers to cut it to — they are the film's own",
  "structural beats, so a track edited to them will land with the picture.",
  "",
  "The film is watched with the sound off. Nothing in the picture depends on a",
  "musical cue, and nothing should be added that does.",
  "",
  "| Marker | Time | Intent |",
  "|---|---|---|",
  `| Track in | ${clock(0)} | Enter under the ledger grid, low. |`,
  `| First lift | ${clock(starts[1])} | The contract resolves both schemas. |`,
  `| Hold low | ${clock(starts[1] + 17)} | The referred-for-review beat must be read, not scored. |`,
  `| Resolve | ${clock(starts[2])} | The governed outputs land together. |`,
  `| Sustain | ${clock(starts[3])} | Three channels, one answer — steady, unhurried. |`,
  `| Final statement | ${clock(starts[4])} | The lockup moves; let the last chord ring. |`,
  `| Track out | ${clock(total)} | Fade to silence with the final frame. |`,
];
writeFileSync(join(OUT, "music-markers.md"), music.join("\n"), "utf8");

console.log(`[script] total run time ${clock(total)} (${total.toFixed(1)}s)`);
console.log(`[script] ${cues.length} caption cues`);
for (const name of [
  "voiceover-script.md",
  "captions.srt",
  "captions.vtt",
  "scene-timings.csv",
  "music-markers.md",
]) {
  console.log(`[script] out/${name}`);
}
