#!/usr/bin/env python3
"""scripts/mi_query_calibration.py

Run the generative MI-query golden harness and write a markdown calibration
report: how many cases ran, the pass/fail split, failures by class
(parser / executor / renderer), correctly-rejected unsupported concepts, and a
sample of exercised queries per class.

Usage:
    python scripts/mi_query_calibration.py                 # writes docs/mi_query_calibration_report.md
    python scripts/mi_query_calibration.py --out PATH      # custom output path
    python scripts/mi_query_calibration.py --print         # also print summary to stdout

Deterministic and offline (no LLM/network) — safe for CI.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mi_agent import mi_query_harness as H


_CLASS_MEANING = {
    "parser": "the query's dimension/metric was not recognised by the parser",
    "executor": "a parsed dimension/metric was not applied in execution (silent drop)",
    "renderer": "an applied dimension was absent from BOTH the chart axes and the table",
    "rejection": "an unsupported concept was answered with a stand-in instead of refused",
    "error": "the pipeline raised or returned a hard validation error",
}


def _kind_examples(results, kind, n=4):
    out = []
    for r in results:
        if r.case.kind == kind and r.ok:
            out.append(r.case.query)
        if len(out) >= n:
            break
    return out


def build_markdown(results, summary) -> str:
    total = summary["total"]
    passed = summary["passed"]
    failed = summary["failed"]
    lines = []
    A = lines.append
    A("# MI `/query` Dimension-Invariant Calibration Report")
    A("")
    A("_Generated by `scripts/mi_query_calibration.py` from the registry-driven "
      "golden harness (`mi_agent/mi_query_harness.py`). Deterministic and offline "
      "— no LLM/network._")
    A("")
    A("## Headline")
    A("")
    A(f"- **Cases run:** {total}")
    A(f"- **Passed:** {passed}  ")
    A(f"- **Failed:** {failed}  ")
    A(f"- **Pass rate:** {summary['pass_rate'] * 100:.2f}%")
    A(f"- **Unsupported concepts correctly refused:** {summary['rejections_correct']}")
    A("")
    A("The single guarantee under test: every grouping dimension the parser "
      "recognises is either **applied** (present in the executor group columns / "
      "result columns and surfaced on the chart axes or table) or **explicitly "
      "rejected** with a reason — **never silently dropped**. A requested metric "
      "must likewise appear in the result payload rather than being substituted "
      "with the default balance.")
    A("")

    A("## Coverage by query class")
    A("")
    A("| Class | Passed | Total | Pass rate |")
    A("|---|---:|---:|---:|")
    for kind, agg in summary["by_kind"].items():
        rate = (agg["passed"] / agg["total"] * 100) if agg["total"] else 0.0
        A(f"| {kind} | {agg['passed']} | {agg['total']} | {rate:.0f}% |")
    A("")

    A("## Failures by class")
    A("")
    if not summary["failures_by_class"]:
        A("None — every generated query held the invariant.")
    else:
        A("| Class | Count | Meaning |")
        A("|---|---:|---|")
        for cls, count in sorted(summary["failures_by_class"].items()):
            A(f"| {cls} | {count} | {_CLASS_MEANING.get(cls, '')} |")
        A("")
        A("### Failing cases")
        A("")
        for r in results:
            if not r.ok:
                A(f"- `[{r.failure_class}]` **{r.case.query}** — {r.detail}")
    A("")

    A("## Dimensions exercised")
    A("")
    A("Registry dimensions that both parsed and executed against the fixture "
      "(the harness discovers these — it does not hardcode them):")
    A("")
    for d in summary["usable_dimensions"]:
        A(f"- `{d}`")
    A("")

    A("## Sample queries per class (passing)")
    A("")
    for kind in summary["by_kind"]:
        ex = _kind_examples(results, kind)
        if ex:
            A(f"**{kind}**")
            for q in ex:
                A(f"  - {q}")
            A("")

    lim = summary.get("grouped_filter_limitation")
    if lim is not None:
        A("## Known limitations")
        A("")
        A("**Grouped query + value filter** — evidenced from live behaviour:")
        A("")
        A(f"- Probe: `{lim['query']}`")
        A(f"- Filter parsed into the spec: **{lim['filter_parsed']}**")
        A(f"- Filter applied (reconciliation): **{lim['filters_applied']}** "
          f"({lim['records_after_filters']} of {lim['total_records']} records)")
        A(f"- Omission surfaced to the user (warning): **{lim['omission_surfaced']}**")
        A(f"- Supported today: **{lim['supported']}**")
        A("")
        A("A value filter combined with a grouping (`… by <dim> where <measure> "
          "above <x>`) is **not** applied today, and the omission is not yet "
          "surfaced as a warning. The supported filtered shape is the ungrouped "
          "filtered KPI (`how many loans have LTV above 50%`), verified by the "
          "`filtered_kpi` class above. Recommended follow-up: extend the "
          "fail-closed guard to filters (warn/refuse when a recognised filter "
          "phrase is not applied) and add grouped+filter parsing.")
        A("")

    A("## Correctly-rejected unsupported concepts")
    A("")
    for r in results:
        if r.case.kind == "rejection":
            mark = "refused ✅" if r.ok else "ANSWERED ⚠️"
            A(f"- {r.case.query} — {mark}")
    A("")

    A("## How to reproduce")
    A("")
    A("```bash")
    A("# The invariant regression (fast, offline):")
    A("python -m pytest mi_agent/tests/test_mi_query_invariants.py -q")
    A("")
    A("# Regenerate this report:")
    A("python scripts/mi_query_calibration.py")
    A("```")
    A("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(_REPO_ROOT / "docs" / "mi_query_calibration_report.md"))
    ap.add_argument("--print", dest="do_print", action="store_true")
    args = ap.parse_args()

    results, summary = H.run_suite()
    md = build_markdown(results, summary)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out} ({summary['passed']}/{summary['total']} passed, "
          f"{summary['pass_rate'] * 100:.2f}%)")
    if args.do_print:
        print(md)
    return 0 if summary["failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
