#!/usr/bin/env python3
"""scripts/mi_query_calibration.py

Run the generative MI-query golden harness and write a markdown calibration
report: how many cases ran, the pass/fail split, failures by class
(parser / executor / renderer), correctly-rejected unsupported concepts, and a
sample of exercised queries per class.

Usage:
    python scripts/mi_query_calibration.py                 # writes docs/mi_query_calibration_report.md
    python scripts/mi_query_calibration.py --out PATH      # custom output path
    python scripts/mi_query_calibration.py --print         # also print summary to stdout

Deterministic and offline (no LLM/network) — safe for CI.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mi_agent import mi_query_harness as H


_CLASS_MEANING = {
    "parser": "the query's dimension/metric was not recognised by the parser",
    "executor": "a parsed dimension/metric was not applied in execution (silent drop)",
    "filter": "a parsed value filter was not applied to the execution mask (silent omission)",
    "renderer": "an applied dimension was absent from BOTH the chart axes and the table",
    "rejection": "an unsupported concept was answered with a stand-in instead of refused",
    "error": "the pipeline raised or returned a hard validation error",
}


def _kind_examples(results, kind, n=4):
    out = []
    for r in results:
        if r.case.kind == kind and r.ok:
            out.append(r.case.query)
        if len(out) >= n:
            break
    return out


def build_markdown(results, summary) -> str:
    total = summary["total"]
    passed = summary["passed"]
    failed = summary["failed"]
    lines = []
    A = lines.append
    A("# MI `/query` Dimension-Invariant Calibration Report")
    A("")
    A("_Generated by `scripts/mi_query_calibration.py` from the registry-driven "
      "golden harness (`mi_agent/mi_query_harness.py`). Deterministic and offline "
      "— no LLM/network._")
    A("")
    A("## Headline")
    A("")
    A(f"- **Cases run:** {total}")
    A(f"- **Passed:** {passed}  ")
    A(f"- **Failed:** {failed}  ")
    A(f"- **Pass rate:** {summary['pass_rate'] * 100:.2f}%")
    A(f"- **Unsupported concepts correctly refused:** {summary['rejections_correct']}")
    A("")
    A("The single guarantee under test: every grouping dimension the parser "
      "recognises is either **applied** (present in the executor group columns / "
      "result columns and surfaced on the chart axes or table) or **explicitly "
      "rejected** with a reason — **never silently dropped**. A requested metric "
      "must likewise appear in the result payload rather than being substituted "
      "with the default balance.")
    A("")

    A("## Fail-closed invariants (tracked separately)")
    A("")
    dim = summary.get("dimension_invariant", {})
    filt = summary.get("filter_invariant", {})
    A("| Invariant | Cases checked | Held | Breached |")
    A("|---|---:|---:|---:|")
    A(f"| Dimension (parsed dim applied or explicitly rejected) | "
      f"{dim.get('checked', 0)} | {dim.get('held', 0)} | {dim.get('breached', 0)} |")
    A(f"| Filter (parsed filter applied or explicitly surfaced) | "
      f"{filt.get('checked', 0)} | {filt.get('held', 0)} | {filt.get('breached', 0)} |")
    A("")
    A(f"Value filters were genuinely exercised on **{summary.get('filters_exercised', 0)}** "
      "cases (parsed AND applied to the execution mask). A parsed filter that is "
      "neither applied nor explicitly surfaced fails the query closed rather than "
      "returning silently unfiltered data.")
    A("")

    A("## Coverage by query class")
    A("")
    A("| Class | Passed | Total | Pass rate |")
    A("|---|---:|---:|---:|")
    for kind, agg in summary["by_kind"].items():
        rate = (agg["passed"] / agg["total"] * 100) if agg["total"] else 0.0
        A(f"| {kind} | {agg['passed']} | {agg['total']} | {rate:.0f}% |")
    A("")

    A("## Failures by class")
    A("")
    if not summary["failures_by_class"]:
        A("None — every generated query held the invariant.")
    else:
        A("| Class | Count | Meaning |")
        A("|---|---:|---|")
        for cls, count in sorted(summary["failures_by_class"].items()):
            A(f"| {cls} | {count} | {_CLASS_MEANING.get(cls, '')} |")
        A("")
        A("### Failing cases")
        A("")
        for r in results:
            if not r.ok:
                A(f"- `[{r.failure_class}]` **{r.case.query}** — {r.detail}")
    A("")

    A("## Dimensions exercised")
    A("")
    A("Registry dimensions that both parsed and executed against the fixture "
      "(the harness discovers these — it does not hardcode them):")
    A("")
    for d in summary["usable_dimensions"]:
        A(f"- `{d}`")
    A("")

    A("## Sample queries per class (passing)")
    A("")
    for kind in summary["by_kind"]:
        ex = _kind_examples(results, kind)
        if ex:
            A(f"**{kind}**")
            for q in ex:
                A(f"  - {q}")
            A("")

    sup = summary.get("grouped_filter_support")
    if sup is not None:
        A("## Grouped query + value filter (now supported)")
        A("")
        A("Evidenced from live behaviour:")
        A("")
        A(f"- Probe: `{sup['query']}`")
        A(f"- Filter parsed into the spec: **{sup['filter_parsed']}**")
        A(f"- Filter applied (reconciliation): **{sup['filters_applied']}** "
          f"({sup['records_after_filters']} of {sup['total_records']} records)")
        A(f"- Supported: **{sup['supported']}**")
        A("")
        A("A value filter combined with a grouping (`… by <dim> where <measure> "
          "above <x>`, ranges, and categorical `… for joint borrowers`) is now "
          "applied to the execution mask **before** grouping — both the grouping "
          "and the filter survive. The fail-closed **filter invariant** refuses "
          "the query if a parsed filter is not applied, so unfiltered grouped "
          "data is never returned silently. A filter on a field ABSENT from the "
          "dataset is refused or surfaced as unavailable (`filter_unsupported` "
          "class), never silently ignored.")
        A("")

    A("## Correctly-rejected unsupported concepts")
    A("")
    for r in results:
        if r.case.kind == "rejection":
            mark = "refused ✅" if r.ok else "ANSWERED ⚠️"
            A(f"- {r.case.query} — {mark}")
    A("")

    A("## How to reproduce")
    A("")
    A("```bash")
    A("# The invariant regression (fast, offline):")
    A("python -m pytest mi_agent/tests/test_mi_query_invariants.py -q")
    A("")
    A("# Regenerate this report:")
    A("python scripts/mi_query_calibration.py")
    A("```")
    A("")
    return "\n".join(lines)


def build_curated_markdown() -> str:
    """The curated calibration bank section (250+ realistic business questions)."""
    from mi_agent import mi_calibration as CAL
    results, s = CAL.run_bank()
    lines: list = []
    A = lines.append
    A("")
    A("---")
    A("")
    A("# Curated calibration bank (realistic business questions)")
    A("")
    A("Additional to the generated harness above: a hand-curated bank of realistic "
      "lender / investor / credit-committee / portfolio-manager / ops questions, "
      "each with declared expected semantic behaviour "
      "(`config/mi/golden_questions/ere_mi_calibration_250.yaml`, enforced by "
      "`mi_agent/tests/test_mi_calibration_bank.py`).")
    A("")
    A(f"- **Curated questions:** {s['total']}")
    A(f"- **Held their declared expectation:** {s['passed']}")
    A(f"- **Hard failures (non-known-gap):** {s['hard_failures']}")
    A(f"- **Known-gap cases (flagged):** {s['known_gaps']} — "
      f"of which **{s['known_gaps_xfailed']}** currently fail (xfailed with a reason) "
      f"and **{s['known_gaps_passing']}** already meet the ideal (flag can be retired).")
    A(f"- **Pass rate (known gaps counted as not-passing):** {s['pass_rate'] * 100:.1f}%")
    A("")
    A("## Pass / fail by category")
    A("")
    A("| Category | Passed | Total | Known gaps | Hard fails |")
    A("|---|---:|---:|---:|---:|")
    for cat, agg in sorted(s["by_category"].items()):
        hard = agg["total"] - agg["passed"] - agg["known_gap"] \
            if (agg["total"] - agg["passed"]) > agg["known_gap"] else 0
        # hard = cases neither passed nor known_gap
        hardfails = sum(1 for r in results if r.category == cat and not r.ok and not r.known_gap)
        A(f"| {cat} | {agg['passed']} | {agg['total']} | {agg['known_gap']} | {hardfails} |")
    A("")
    A("## Failure classes (hard failures only)")
    A("")
    defects = s["defects_by_class"]
    if not defects:
        A("None — every non-known-gap curated question held its declared expectation "
          "(metric resolution, dimensions applied, filters applied, dimension & filter "
          "invariants, artifact type, reconciliation).")
    else:
        A("| Class | Count |")
        A("|---|---:|")
        for cls, n in sorted(defects.items(), key=lambda kv: -kv[1]):
            A(f"| {cls} | {n} |")
    A("")
    # Correctly-refused unsupported concepts.
    refused = [r for r in results if r.category == "unsupported"]
    A("## Unsupported concepts correctly refused")
    A("")
    for r in refused:
        A(f"- {r.question} — {'refused ✅' if r.ok else 'NOT refused ⚠️'}")
    A("")
    A("## Known gaps / follow-ups (discovered, not loosened)")
    A("")
    A("These curated questions state the IDEAL behaviour; the system does not yet "
      "meet it, so they are xfailed with the reason below rather than having their "
      "expectation weakened.")
    A("")
    seen = set()
    for rid, q, gap in s["known_gap_cases"]:
        key = gap[:60]
        if key in seen:
            A(f"- `{rid}` {q}")
            continue
        seen.add(key)
        A(f"- `{rid}` **{q}** — {gap}")
    A("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(_REPO_ROOT / "docs" / "mi_query_calibration_report.md"))
    ap.add_argument("--print", dest="do_print", action="store_true")
    ap.add_argument("--live-llm", dest="live_llm", action="store_true",
                    help="Also run the Priority-1 cases through the LLM parser "
                         "(requires ANTHROPIC_API_KEY) and print the contract report.")
    args = ap.parse_args()

    if args.live_llm:
        from mi_agent import mi_calibration as CAL
        if not CAL.llm_available():
            print("--live-llm requested but ANTHROPIC_API_KEY is not set; skipping "
                  "the live LLM pass (CI stays deterministic).")
        else:
            print("Live LLM Priority-1 contract report:")
            for row in CAL.run_live_llm_priority():
                mark = "OK" if row["contract_ok"] else "CONTRACT VIOLATION"
                print(f"  [{mark}] {row['question']} — parser={row['parser_mode']} "
                      f"dimInv={row['dimension_invariant_ok']} filtInv={row['filter_invariant_ok']} "
                      f"filters={row['applied_filters']} dims={row['applied_dimensions']}")

    results, summary = H.run_suite()
    md = build_markdown(results, summary) + "\n" + build_curated_markdown()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    from mi_agent import mi_calibration as CAL
    _, cur = CAL.run_bank()
    print(f"wrote {out} (generated {summary['passed']}/{summary['total']}; "
          f"curated {cur['passed']}/{cur['total']} held, {cur['hard_failures']} hard fails, "
          f"{cur['known_gaps']} known gaps)")
    if args.do_print:
        print(md)
    return 0 if (summary["failed"] == 0 and cur["hard_failures"] == 0) else 1


if __name__ == "__main__":
    raise SystemExit(main())
