"""
agents/learning_persistence.py

Persists approved review decisions to the shared alias / enum / config files.

Goal: after month 1, 12 questions.  After month 2, 0 questions.

Three persistence targets:
  1. Field mapping aliases  → aliases_llm_confirmed.yaml
     Format mirrors AliasLearner in llm_mapper_agent.py.
  2. Enum synonyms          → enum_synonyms_confirmed.yaml
     Format mirrors EnumAliasLearner in enum_mapping_agent.py.
  3. Client config values   → approved_config.yaml (merged copy; not overwriting master)

All writes are append-safe and idempotent (duplicates are skipped).
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from agents.review_schemas import (
    EnumDecision,
    MappingDecision,
    QuestionAnswer,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Field mapping aliases
# ---------------------------------------------------------------------------

_ALIAS_FILE = "aliases_llm_confirmed.yaml"


def persist_mapping_decisions(
    decisions: List[MappingDecision],
    aliases_dir: Path,
    session_id: str = "",
) -> int:
    """
    Append approved mapping decisions to aliases_llm_confirmed.yaml.
    Returns count of new aliases written.

    Format written:
        canonical_field_name:
          aliases:
            - raw_header_name
          source: workbench
          confirmed_by: human
    """
    approved = [d for d in decisions if d.approved and d.selected_canonical_field]
    if not approved:
        return 0

    aliases_dir = Path(aliases_dir)
    aliases_dir.mkdir(parents=True, exist_ok=True)
    output_path = aliases_dir / _ALIAS_FILE

    existing: Dict[str, Any] = {}
    if output_path.exists():
        try:
            existing = yaml.safe_load(output_path.read_text(encoding="utf-8")) or {}
            if not isinstance(existing, dict):
                existing = {}
        except Exception as exc:
            logger.warning("Could not parse %s: %s — starting fresh.", output_path, exc)

    # Collect all already-known aliases (normalised) across all alias files to dedup
    known_normalised: set = set()
    for yaml_file in aliases_dir.glob("aliases_*.yaml"):
        try:
            data = yaml.safe_load(yaml_file.read_text(encoding="utf-8")) or {}
            _collect_alias_strings(data, known_normalised)
        except Exception:
            pass

    added = 0
    for decision in approved:
        raw = decision.raw_field.strip()
        target = decision.selected_canonical_field
        if not raw or not target:
            continue

        raw_norm = _normalise(raw)
        if raw_norm in known_normalised:
            logger.debug("Alias '%s' already exists — skipping.", raw)
            continue

        entry = existing.setdefault(target, {"aliases": [], "source": "workbench", "confirmed_by": "human"})
        if isinstance(entry, list):
            existing[target] = {"aliases": list(entry), "source": "workbench", "confirmed_by": "human"}
            entry = existing[target]

        existing_norms = {_normalise(a) for a in entry.get("aliases", [])}
        if raw_norm not in existing_norms:
            entry.setdefault("aliases", []).append(raw)
            known_normalised.add(raw_norm)
            added += 1
            logger.info("Alias persisted: '%s' → '%s'", raw, target)

    if added > 0:
        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        header = f"# Auto-generated by Onboarding Workbench\n# Last updated: {ts}\n# Session: {session_id}\n"
        output_path.write_text(
            header + yaml.dump(existing, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )
        logger.info("Wrote %d new alias(es) to %s", added, output_path)

    return added


def _collect_alias_strings(data: Dict[str, Any], result: set) -> None:
    for k, v in data.items():
        if isinstance(v, list):
            for a in v:
                result.add(_normalise(str(a)))
        elif isinstance(v, dict):
            if "aliases" in v:
                for a in v.get("aliases", []):
                    result.add(_normalise(str(a)))
            else:
                _collect_alias_strings(v, result)


def _normalise(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip()).lower()


# ---------------------------------------------------------------------------
# Enum synonyms
# ---------------------------------------------------------------------------

def persist_enum_decisions(
    decisions: List[EnumDecision],
    enum_synonyms_path: Path,
    namespace: str = "global",
    session_id: str = "",
) -> int:
    """
    Append approved enum decisions to enum_synonyms_confirmed.yaml.
    Returns count of new synonyms written.

    Format written:
        global:
          field_name:
            raw_value: canonical_value
    """
    approved = [d for d in decisions if d.approved and d.selected_value]
    if not approved:
        return 0

    enum_synonyms_path = Path(enum_synonyms_path)
    enum_synonyms_path.parent.mkdir(parents=True, exist_ok=True)

    existing: Dict[str, Any] = {}
    if enum_synonyms_path.exists():
        try:
            existing = yaml.safe_load(enum_synonyms_path.read_text(encoding="utf-8")) or {}
            if not isinstance(existing, dict):
                existing = {}
        except Exception as exc:
            logger.warning("Could not parse %s: %s — starting fresh.", enum_synonyms_path, exc)

    ns_block: Dict[str, Any] = existing.setdefault(namespace, {})
    if not isinstance(ns_block, dict):
        ns_block = {}
        existing[namespace] = ns_block

    added = 0
    for decision in approved:
        raw = decision.raw_value.strip()
        canonical = decision.selected_value
        fname = decision.field_name.strip()
        if not raw or not canonical or not fname:
            continue

        raw_norm = _normalise(raw)
        field_block: Dict[str, Any] = ns_block.setdefault(fname, {})
        existing_norms = {_normalise(k) for k in field_block}
        if raw_norm not in existing_norms:
            field_block[raw] = canonical
            added += 1
            logger.info("Enum synonym persisted: [%s] '%s' → '%s'", fname, raw, canonical)

    if added > 0:
        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        header = f"# Auto-generated by Onboarding Workbench\n# Last updated: {ts}\n# Session: {session_id}\n"
        enum_synonyms_path.write_text(
            header + yaml.dump(existing, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )
        logger.info("Wrote %d new enum synonym(s) to %s", added, enum_synonyms_path)

    return added


# ---------------------------------------------------------------------------
# Config values
# ---------------------------------------------------------------------------

def persist_config_answers(
    answers: List[QuestionAnswer],
    draft_config_path: Path,
    output_config_path: Path,
    session_id: str = "",
) -> int:
    """
    Merge approved question answers into the draft config and write the result
    to output_config_path (the approved config).  Returns count of values applied.

    This does NOT overwrite the master client config — it produces a
    run-specific approved config that the agent will use on re-run.
    """
    approved = [a for a in answers if a.approved and a.answer.strip()]
    if not approved:
        # Just copy draft forward
        if draft_config_path.exists():
            output_config_path.write_text(
                draft_config_path.read_text(encoding="utf-8"), encoding="utf-8"
            )
        return 0

    merged: Dict[str, Any] = {}
    if draft_config_path.exists():
        try:
            merged = yaml.safe_load(draft_config_path.read_text(encoding="utf-8")) or {}
        except Exception as exc:
            logger.warning("Could not load draft config: %s", exc)

    applied = 0
    for answer in approved:
        # question_id format: q_portfolio_asset_class → portfolio.asset_class
        config_key = answer.question_id.removeprefix("q_").replace("_", ".", 1)
        _nested_set(merged, config_key, answer.answer.strip())
        applied += 1
        logger.info("Config answer applied: %s = %s", config_key, answer.answer.strip())

    if applied > 0:
        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        header = f"# Approved config — generated by Onboarding Workbench {ts}\n# Session: {session_id}\n"
        output_config_path.write_text(
            header + yaml.dump(merged, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )
        logger.info("Approved config written to %s", output_config_path)

    return applied


def _nested_set(d: Dict[str, Any], dotted_key: str, val: Any) -> None:
    parts = dotted_key.split(".")
    for p in parts[:-1]:
        d = d.setdefault(p, {})
    d[parts[-1]] = val
