"""mi_workflows/semantics — runtime loader for the Business Semantics Registry.

The registry (``config/business_semantics_registry.yaml``) is generated by
``scripts/build_business_semantics_registry.py`` and validated by
``tests/test_business_semantics_registry.py``. Until now nothing consumed it at
runtime. This module is the single runtime reader:

  * :func:`load_business_semantics` — the parsed, immutable registry, cached by
    path + mtime so a regenerated file is picked up without a restart;
  * :func:`semantics_context_resolver` — the ``semantics_resolver``
    implementation for the seam prepared in
    ``mi_agent_api.dependencies.CapabilityDependencies``: given one parsed
    question it returns the governed business-term metadata the parse names,
    which then travels on ``ParsedQuestion.semantics_context`` →
    ``RouteRequest.semantics_context`` to every recogniser and handler.

Nothing here interprets the metadata — workflows do that. This module only
loads, indexes and hands over exactly what the registry says.
"""

from __future__ import annotations

import logging
import os
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Tuple

import yaml

logger = logging.getLogger("mi_workflows.semantics")

#: Environment override, mirroring ``TRAKT_PORTFOLIO_REGISTRY`` for the
#: portfolio metadata overlay.
ENV_REGISTRY_PATH = "TRAKT_BUSINESS_SEMANTICS_REGISTRY"

DEFAULT_REGISTRY_PATH = (
    Path(__file__).resolve().parent.parent / "config" / "business_semantics_registry.yaml")

#: Workflow tags the generator governs (metadata.taxonomy.workflow_tags).
TAG_PORTFOLIO_COMPARISON = "portfolio_comparison"
TAG_PERIOD_CHANGE = "period_change"

#: Portfolio-comparability states (metadata.taxonomy.portfolio_comparability).
COMPARABLE = "comparable"
REQUIRES_SCALE_ALIGNMENT = "requires_scale_alignment"
WITHIN_ASSET_CLASS_ONLY = "within_asset_class_only"
NOT_COMPARABLE = "not_comparable"

#: Asset-applicability value meaning "applies to every governed asset class".
CROSS_ASSET = "cross_asset"


@dataclass(frozen=True)
class SemanticEntry:
    """One governed field entry, exactly as the registry declares it."""

    source_field: str
    display_name: str
    analytical_concept: str
    analytical_role: str
    temporality: str
    categories: Tuple[str, ...]
    workflow_tags: Tuple[str, ...]
    directionality: str
    default_aggregation: str
    weight_field: Optional[str]
    share_basis: Optional[str]
    portfolio_comparability: str
    supports_materiality_assessment: bool
    asset_applicability: Tuple[str, ...]
    confidence: str
    rationale: str

    def tagged(self, workflow_tag: str) -> bool:
        return workflow_tag in self.workflow_tags

    def is_cross_asset(self) -> bool:
        return CROSS_ASSET in self.asset_applicability

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source_field": self.source_field,
            "display_name": self.display_name,
            "analytical_concept": self.analytical_concept,
            "analytical_role": self.analytical_role,
            "temporality": self.temporality,
            "categories": list(self.categories),
            "workflow_tags": list(self.workflow_tags),
            "directionality": self.directionality,
            "default_aggregation": self.default_aggregation,
            "weight_field": self.weight_field,
            "share_basis": self.share_basis,
            "portfolio_comparability": self.portfolio_comparability,
            "supports_materiality_assessment": self.supports_materiality_assessment,
            "asset_applicability": list(self.asset_applicability),
            "confidence": self.confidence,
            "rationale": self.rationale,
        }


@dataclass(frozen=True)
class BusinessSemanticsRegistry:
    """The parsed registry: version identity, taxonomy and entries."""

    version: str
    schema_version: int
    source_registry: str
    taxonomy: Mapping[str, Any]
    entries: Mapping[str, SemanticEntry] = field(default_factory=dict)

    def get(self, source_field: Optional[str]) -> Optional[SemanticEntry]:
        if not source_field:
            return None
        return self.entries.get(str(source_field))

    def for_workflow(self, workflow_tag: str) -> Tuple[SemanticEntry, ...]:
        """Entries governed for one workflow, in deterministic field order."""
        return tuple(self.entries[name] for name in sorted(self.entries)
                     if self.entries[name].tagged(workflow_tag))

    def __len__(self) -> int:
        return len(self.entries)

    def __contains__(self, source_field: object) -> bool:
        return source_field in self.entries


def registry_path() -> Path:
    override = (os.environ.get(ENV_REGISTRY_PATH) or "").strip()
    return Path(override) if override else DEFAULT_REGISTRY_PATH


def _entry_from_dict(name: str, raw: Mapping[str, Any]) -> SemanticEntry:
    return SemanticEntry(
        source_field=str(raw.get("source_field") or name),
        display_name=str(raw.get("display_name") or name),
        analytical_concept=str(raw.get("analytical_concept") or ""),
        analytical_role=str(raw.get("analytical_role") or ""),
        temporality=str(raw.get("temporality") or ""),
        categories=tuple(raw.get("categories") or ()),
        workflow_tags=tuple(raw.get("workflow_tags") or ()),
        directionality=str(raw.get("directionality") or "neutral"),
        default_aggregation=str(raw.get("default_aggregation") or ""),
        weight_field=raw.get("weight_field") or None,
        share_basis=raw.get("share_basis") or None,
        portfolio_comparability=str(raw.get("portfolio_comparability") or NOT_COMPARABLE),
        supports_materiality_assessment=bool(raw.get("supports_materiality_assessment")),
        asset_applicability=tuple(raw.get("asset_applicability") or ()),
        confidence=str(raw.get("confidence") or "low"),
        rationale=str(raw.get("rationale") or ""),
    )


# Cache one parsed registry per path, invalidated by mtime — the same pattern
# the dataset layer uses. Parsing 5,400 lines of YAML per question would be
# pure waste; a stale cache after regeneration would be wrong.
_CACHE_LOCK = threading.Lock()
_CACHE: Dict[str, Tuple[float, BusinessSemanticsRegistry]] = {}


def load_business_semantics(path: Optional[os.PathLike] = None) -> BusinessSemanticsRegistry:
    """The governed Business Semantics Registry. Raises if unreadable.

    Callers on a user-facing path must treat a raise as a controlled
    "governed semantics unavailable" outcome, never a 500.
    """
    p = Path(path) if path is not None else registry_path()
    key = str(p)
    mtime = p.stat().st_mtime
    with _CACHE_LOCK:
        cached = _CACHE.get(key)
        if cached is not None and cached[0] == mtime:
            return cached[1]
    with open(p, "r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    metadata = raw.get("metadata") or {}
    fields = raw.get("fields") or {}
    registry = BusinessSemanticsRegistry(
        version=str(metadata.get("version") or "unknown"),
        schema_version=int(metadata.get("schema_version") or 0),
        source_registry=str(metadata.get("source_registry") or ""),
        taxonomy=dict(metadata.get("taxonomy") or {}),
        entries={name: _entry_from_dict(name, entry or {})
                 for name, entry in fields.items()},
    )
    with _CACHE_LOCK:
        _CACHE[key] = (mtime, registry)
    return registry


def reset_cache() -> None:
    """Drop cached registries (tests, and after an explicit regeneration)."""
    with _CACHE_LOCK:
        _CACHE.clear()


def semantics_context_resolver(question: str, spec: Any,
                               semantics: Mapping[str, Any]) -> Dict[str, Any]:
    """``semantics_resolver`` for the prepared dependency seam.

    Returns the governed metadata for the fields the SINGLE parse resolved
    (metric, dimension), plus the registry's version identity — enough for a
    recogniser or workflow to know what the question's terms mean without
    re-reading the registry. Small and side-effect free by design; the full
    registry stays behind :func:`load_business_semantics`.

    A fault yields ``{}``: the registry is additive, and an unavailable
    registry must never break a query (``ParsedQuestion.parse`` also swallows a
    raise — this is defence in depth, not the only guard).
    """
    try:
        registry = load_business_semantics()
    except Exception as exc:  # noqa: BLE001 - additive metadata, never a failure
        logger.info("business semantics registry unavailable: %s", exc)
        return {}
    context: Dict[str, Any] = {
        "bsr_version": registry.version,
        "bsr_schema_version": registry.schema_version,
    }
    resolved: Dict[str, Any] = {}
    for role in ("metric", "dimension"):
        entry = registry.get(getattr(spec, role, None))
        if entry is not None:
            resolved[role] = entry.to_dict()
    if resolved:
        context["fields"] = resolved
    return context
